// Base de données aliments — muscumoov nutrition
// Module JS plain, pas de bundler. Charger via <script src="lib/foods-db.js"></script>
// Toutes les valeurs nutritionnelles sont pour 100 g (portionG = portion réelle typique).

window.FOOD_CATEGORIES = [
  { id: 'breakfast',      label: 'Petit-déjeuner',     icon: '🍳' },
  { id: 'burgers-grill',  label: 'Burgers & grill',    icon: '🍔' },
  { id: 'pizza',          label: 'Pizza',              icon: '🍕' },
  { id: 'sandwiches',     label: 'Sandwiches',         icon: '🥪' },
  { id: 'salads-healthy', label: 'Salades & healthy',  icon: '🥗' },
  { id: 'mexican',        label: 'Mexicain',           icon: '🌮' },
  { id: 'asian',          label: 'Asiatique',          icon: '🍜' },
  { id: 'italian',        label: 'Italien',            icon: '🍝' },
  { id: 'comfort-us',     label: 'Comfort food US',    icon: '🍗' },
  { id: 'international',  label: 'International',      icon: '🌍' },
  { id: 'veg-vegan',      label: 'Végé & Vegan',       icon: '🌱' },
  { id: 'desserts',       label: 'Desserts',           icon: '🍰' },
  { id: 'snacks',         label: 'Snacks',             icon: '🥨' },
  { id: 'drinks',         label: 'Boissons',           icon: '☕' },
];

window.FOODS_DB = [
  // ============ PETIT-DÉJEUNER ============
  {
    id: 'eggs-scrambled',
    name: 'Œufs brouillés',
    category: 'breakfast',
    portionG: 100,
    kcal: 148, protein: 10, fat: 11, carbs: 2,
    fiber: 0, sugar: 1, sodium: 145,
    calcium: 50, iron: 1.2, potassium: 130, vitaminD: 80,
    allergens: ['œuf', 'lait'],
    tags: ['vegetarian', 'halal', 'gluten-free', 'high-protein', 'low-carb'],
    notes: 'Riche en protéines et vitamine B12'
  },
  {
    id: 'omelette',
    name: 'Omelette nature',
    category: 'breakfast',
    portionG: 150,
    kcal: 154, protein: 11, fat: 12, carbs: 1,
    fiber: 0, sugar: 1, sodium: 155,
    calcium: 48, iron: 1.3, potassium: 135, vitaminD: 82,
    allergens: ['œuf', 'lait'],
    tags: ['vegetarian', 'halal', 'gluten-free', 'high-protein', 'low-carb']
  },
  {
    id: 'bacon',
    name: 'Bacon',
    category: 'breakfast',
    portionG: 30,
    kcal: 541, protein: 37, fat: 42, carbs: 1,
    fiber: 0, sugar: 0, sodium: 1717,
    calcium: 11, iron: 1.4, potassium: 565, vitaminD: 25,
    allergens: [],
    tags: ['gluten-free', 'dairy-free', 'high-protein', 'low-carb'],
    notes: 'Très sodé'
  },
  {
    id: 'breakfast-sausage',
    name: 'Saucisses petit-déj',
    category: 'breakfast',
    portionG: 60,
    kcal: 300, protein: 13, fat: 27, carbs: 2,
    fiber: 0, sugar: 1, sodium: 740,
    calcium: 14, iron: 1.1, potassium: 220, vitaminD: 30,
    allergens: [],
    tags: ['gluten-free', 'dairy-free', 'high-protein'],
    notes: 'Lipides élevés'
  },
  {
    id: 'hash-browns',
    name: 'Hash browns',
    category: 'breakfast',
    portionG: 100,
    kcal: 265, protein: 3, fat: 14, carbs: 32,
    fiber: 3, sugar: 1, sodium: 380,
    calcium: 12, iron: 0.8, potassium: 420, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free', 'high-carb']
  },
  {
    id: 'pancakes',
    name: 'Pancakes',
    category: 'breakfast',
    portionG: 120,
    kcal: 227, protein: 6, fat: 10, carbs: 28,
    fiber: 1, sugar: 8, sodium: 439,
    calcium: 100, iron: 1.6, potassium: 130, vitaminD: 25,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['vegetarian', 'high-carb'],
    notes: 'Glucides ++'
  },
  {
    id: 'waffles',
    name: 'Gaufres',
    category: 'breakfast',
    portionG: 80,
    kcal: 291, protein: 8, fat: 14, carbs: 33,
    fiber: 2, sugar: 9, sodium: 511,
    calcium: 120, iron: 2.1, potassium: 140, vitaminD: 30,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['vegetarian', 'high-carb'],
    notes: 'Souvent sucrées'
  },
  {
    id: 'french-toast',
    name: 'French toast',
    category: 'breakfast',
    portionG: 130,
    kcal: 229, protein: 8, fat: 11, carbs: 25,
    fiber: 1, sugar: 6, sodium: 380,
    calcium: 110, iron: 1.8, potassium: 145, vitaminD: 35,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'bagel',
    name: 'Bagel nature',
    category: 'breakfast',
    portionG: 110,
    kcal: 257, protein: 10, fat: 1.5, carbs: 53,
    fiber: 2, sugar: 6, sodium: 480,
    calcium: 50, iron: 3.2, potassium: 95, vitaminD: 0,
    allergens: ['gluten'],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free', 'high-carb'],
    notes: 'Énergie rapide'
  },
  {
    id: 'muffin-blueberry',
    name: 'Muffin myrtilles',
    category: 'breakfast',
    portionG: 110,
    kcal: 377, protein: 5, fat: 14, carbs: 56,
    fiber: 2, sugar: 30, sodium: 380,
    calcium: 60, iron: 1.4, potassium: 120, vitaminD: 8,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'donut-glazed',
    name: 'Donut glacé',
    category: 'breakfast',
    portionG: 60,
    kcal: 421, protein: 5, fat: 23, carbs: 51,
    fiber: 1, sugar: 23, sodium: 326,
    calcium: 25, iron: 1.5, potassium: 80, vitaminD: 0,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'croissant',
    name: 'Croissant',
    category: 'breakfast',
    portionG: 60,
    kcal: 406, protein: 8, fat: 21, carbs: 46,
    fiber: 3, sugar: 11, sodium: 467,
    calcium: 37, iron: 2.0, potassium: 110, vitaminD: 5,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'cereal-cornflakes',
    name: 'Céréales (cornflakes)',
    category: 'breakfast',
    portionG: 40,
    kcal: 357, protein: 7, fat: 0.4, carbs: 84,
    fiber: 3, sugar: 8, sodium: 729,
    calcium: 6, iron: 8.0, potassium: 125, vitaminD: 100,
    allergens: ['gluten'],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free', 'high-carb']
  },
  {
    id: 'granola',
    name: 'Granola',
    category: 'breakfast',
    portionG: 50,
    kcal: 471, protein: 10, fat: 20, carbs: 64,
    fiber: 7, sugar: 24, sodium: 26,
    calcium: 75, iron: 3.9, potassium: 330, vitaminD: 0,
    allergens: ['gluten', 'fruits-à-coque'],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free', 'high-carb']
  },
  {
    id: 'greek-yogurt',
    name: 'Yaourt grec',
    category: 'breakfast',
    portionG: 170,
    kcal: 97, protein: 10, fat: 4, carbs: 4,
    fiber: 0, sugar: 4, sodium: 35,
    calcium: 115, iron: 0.1, potassium: 141, vitaminD: 0,
    allergens: ['lait'],
    tags: ['vegetarian', 'halal', 'gluten-free', 'high-protein', 'low-carb'],
    notes: 'Calcium ++'
  },
  {
    id: 'fresh-fruit-mix',
    name: 'Fruits frais (mélange)',
    category: 'breakfast',
    portionG: 150,
    kcal: 60, protein: 1, fat: 0.3, carbs: 15,
    fiber: 2, sugar: 12, sodium: 2,
    calcium: 15, iron: 0.4, potassium: 220, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'oatmeal',
    name: 'Oatmeal (porridge)',
    category: 'breakfast',
    portionG: 250,
    kcal: 71, protein: 2.5, fat: 1.4, carbs: 12,
    fiber: 1.7, sugar: 0.5, sodium: 4,
    calcium: 9, iron: 0.9, potassium: 70, vitaminD: 0,
    allergens: ['gluten'],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free', 'high-carb']
  },
  {
    id: 'breakfast-burrito',
    name: 'Breakfast burrito',
    category: 'breakfast',
    portionG: 250,
    kcal: 215, protein: 10, fat: 10, carbs: 22,
    fiber: 2, sugar: 2, sodium: 480,
    calcium: 110, iron: 2.0, potassium: 200, vitaminD: 15,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'breakfast-sandwich',
    name: 'Breakfast sandwich',
    category: 'breakfast',
    portionG: 160,
    kcal: 268, protein: 13, fat: 14, carbs: 23,
    fiber: 1, sugar: 3, sodium: 730,
    calcium: 130, iron: 2.2, potassium: 175, vitaminD: 20,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['high-protein']
  },
  {
    id: 'avocado-toast',
    name: 'Toast avocat',
    category: 'breakfast',
    portionG: 150,
    kcal: 220, protein: 6, fat: 13, carbs: 22,
    fiber: 6, sugar: 2, sodium: 280,
    calcium: 40, iron: 1.4, potassium: 380, vitaminD: 0,
    allergens: ['gluten'],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free']
  },
  {
    id: 'biscuits-gravy',
    name: 'Biscuits & gravy',
    category: 'breakfast',
    portionG: 220,
    kcal: 290, protein: 7, fat: 17, carbs: 27,
    fiber: 1, sugar: 2, sodium: 770,
    calcium: 90, iron: 2.0, potassium: 160, vitaminD: 10,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'fruit-smoothie',
    name: 'Smoothie fruits',
    category: 'breakfast',
    portionG: 350,
    kcal: 85, protein: 1, fat: 0.5, carbs: 20,
    fiber: 1.5, sugar: 17, sodium: 15,
    calcium: 30, iron: 0.3, potassium: 230, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free'],
    notes: 'Sucres naturels'
  },

  // ============ BURGERS & GRILL ============
  {
    id: 'cheeseburger',
    name: 'Cheeseburger',
    category: 'burgers-grill',
    portionG: 250,
    kcal: 295, protein: 17, fat: 14, carbs: 30,
    fiber: 2, sugar: 6, sodium: 580,
    calcium: 140, iron: 2.8, potassium: 230, vitaminD: 5,
    allergens: ['gluten', 'lait', 'sésame'],
    tags: ['high-protein'],
    notes: 'Variable selon garniture'
  },
  {
    id: 'hamburger',
    name: 'Hamburger',
    category: 'burgers-grill',
    portionG: 230,
    kcal: 250, protein: 15, fat: 11, carbs: 28,
    fiber: 2, sugar: 5, sodium: 480,
    calcium: 70, iron: 2.5, potassium: 220, vitaminD: 2,
    allergens: ['gluten', 'sésame'],
    tags: ['high-protein']
  },
  {
    id: 'bacon-burger',
    name: 'Bacon burger',
    category: 'burgers-grill',
    portionG: 280,
    kcal: 320, protein: 19, fat: 18, carbs: 27,
    fiber: 2, sugar: 5, sodium: 780,
    calcium: 130, iron: 2.9, potassium: 280, vitaminD: 8,
    allergens: ['gluten', 'lait', 'sésame'],
    tags: ['high-protein']
  },
  {
    id: 'chicken-burger',
    name: 'Chicken burger',
    category: 'burgers-grill',
    portionG: 230,
    kcal: 240, protein: 17, fat: 10, carbs: 20,
    fiber: 1, sugar: 4, sodium: 530,
    calcium: 80, iron: 1.8, potassium: 240, vitaminD: 3,
    allergens: ['gluten', 'sésame'],
    tags: ['halal', 'high-protein']
  },
  {
    id: 'turkey-burger',
    name: 'Turkey burger',
    category: 'burgers-grill',
    portionG: 230,
    kcal: 220, protein: 19, fat: 8, carbs: 19,
    fiber: 1, sugar: 4, sodium: 510,
    calcium: 75, iron: 1.9, potassium: 260, vitaminD: 3,
    allergens: ['gluten', 'sésame'],
    tags: ['halal', 'high-protein']
  },
  {
    id: 'veggie-burger',
    name: 'Veggie burger',
    category: 'burgers-grill',
    portionG: 220,
    kcal: 195, protein: 11, fat: 7, carbs: 22,
    fiber: 5, sugar: 4, sodium: 520,
    calcium: 90, iron: 2.4, potassium: 290, vitaminD: 0,
    allergens: ['gluten', 'soja', 'sésame'],
    tags: ['vegetarian', 'vegan', 'halal']
  },
  {
    id: 'impossible-burger',
    name: 'Impossible burger',
    category: 'burgers-grill',
    portionG: 240,
    kcal: 240, protein: 19, fat: 14, carbs: 9,
    fiber: 3, sugar: 1, sodium: 370,
    calcium: 170, iron: 4.2, potassium: 610, vitaminD: 0,
    allergens: ['soja', 'gluten', 'sésame'],
    tags: ['vegetarian', 'vegan', 'halal', 'high-protein']
  },
  {
    id: 'hot-dog',
    name: 'Hot-dog',
    category: 'burgers-grill',
    portionG: 110,
    kcal: 290, protein: 11, fat: 18, carbs: 22,
    fiber: 1, sugar: 4, sodium: 870,
    calcium: 60, iron: 1.8, potassium: 180, vitaminD: 5,
    allergens: ['gluten'],
    tags: []
  },
  {
    id: 'chili-dog',
    name: 'Chili dog',
    category: 'burgers-grill',
    portionG: 180,
    kcal: 296, protein: 13, fat: 17, carbs: 24,
    fiber: 2, sugar: 5, sodium: 920,
    calcium: 75, iron: 2.4, potassium: 280, vitaminD: 5,
    allergens: ['gluten', 'lait'],
    tags: []
  },
  {
    id: 'corn-dog',
    name: 'Corn dog',
    category: 'burgers-grill',
    portionG: 130,
    kcal: 250, protein: 9, fat: 14, carbs: 22,
    fiber: 1, sugar: 6, sodium: 695,
    calcium: 65, iron: 1.7, potassium: 160, vitaminD: 4,
    allergens: ['gluten', 'œuf'],
    tags: []
  },
  {
    id: 'fries',
    name: 'Frites',
    category: 'burgers-grill',
    portionG: 130,
    kcal: 312, protein: 3, fat: 15, carbs: 41,
    fiber: 4, sugar: 0.5, sodium: 210,
    calcium: 10, iron: 0.8, potassium: 580, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'gluten-free', 'dairy-free', 'high-carb'],
    notes: 'Amidon ++'
  },
  {
    id: 'onion-rings',
    name: 'Onion rings',
    category: 'burgers-grill',
    portionG: 100,
    kcal: 411, protein: 5, fat: 22, carbs: 48,
    fiber: 3, sugar: 5, sodium: 565,
    calcium: 65, iron: 1.5, potassium: 170, vitaminD: 0,
    allergens: ['gluten'],
    tags: ['vegetarian', 'high-carb'],
    notes: 'Friture ++'
  },
  {
    id: 'chicken-tenders',
    name: 'Chicken tenders',
    category: 'burgers-grill',
    portionG: 140,
    kcal: 296, protein: 17, fat: 18, carbs: 16,
    fiber: 1, sugar: 1, sodium: 540,
    calcium: 20, iron: 1.1, potassium: 280, vitaminD: 3,
    allergens: ['gluten', 'œuf'],
    tags: ['halal', 'high-protein'],
    notes: 'Fréquent campus'
  },
  {
    id: 'mozzarella-sticks',
    name: 'Mozzarella sticks',
    category: 'burgers-grill',
    portionG: 100,
    kcal: 305, protein: 13, fat: 18, carbs: 22,
    fiber: 1, sugar: 2, sodium: 730,
    calcium: 340, iron: 1.2, potassium: 90, vitaminD: 12,
    allergens: ['gluten', 'lait', 'œuf'],
    tags: ['vegetarian']
  },

  // ============ PIZZA ============
  {
    id: 'pizza-pepperoni',
    name: 'Pizza pepperoni',
    category: 'pizza',
    portionG: 140,
    kcal: 300, protein: 13, fat: 13, carbs: 33,
    fiber: 2, sugar: 4, sodium: 760,
    calcium: 150, iron: 2.3, potassium: 180, vitaminD: 5,
    allergens: ['gluten', 'lait'],
    tags: ['high-carb']
  },
  {
    id: 'pizza-cheese',
    name: 'Pizza fromage',
    category: 'pizza',
    portionG: 130,
    kcal: 266, protein: 11, fat: 10, carbs: 33,
    fiber: 2, sugar: 4, sodium: 598,
    calcium: 188, iron: 2.0, potassium: 170, vitaminD: 4,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian', 'high-carb'],
    notes: 'Source de calcium'
  },
  {
    id: 'pizza-hawaiian',
    name: 'Pizza hawaïenne',
    category: 'pizza',
    portionG: 140,
    kcal: 270, protein: 12, fat: 9, carbs: 34,
    fiber: 2, sugar: 7, sodium: 680,
    calcium: 160, iron: 2.0, potassium: 200, vitaminD: 4,
    allergens: ['gluten', 'lait'],
    tags: ['high-carb']
  },
  {
    id: 'pizza-meat-lovers',
    name: 'Pizza meat lovers',
    category: 'pizza',
    portionG: 150,
    kcal: 330, protein: 16, fat: 17, carbs: 28,
    fiber: 2, sugar: 4, sodium: 850,
    calcium: 170, iron: 2.6, potassium: 230, vitaminD: 6,
    allergens: ['gluten', 'lait'],
    tags: ['high-protein']
  },
  {
    id: 'pizza-bbq-chicken',
    name: 'Pizza BBQ chicken',
    category: 'pizza',
    portionG: 140,
    kcal: 290, protein: 15, fat: 10, carbs: 35,
    fiber: 2, sugar: 9, sodium: 720,
    calcium: 145, iron: 2.0, potassium: 230, vitaminD: 4,
    allergens: ['gluten', 'lait'],
    tags: ['high-protein']
  },
  {
    id: 'pizza-veggie',
    name: 'Pizza végétarienne',
    category: 'pizza',
    portionG: 140,
    kcal: 240, protein: 10, fat: 8, carbs: 33,
    fiber: 3, sugar: 4, sodium: 580,
    calcium: 160, iron: 2.1, potassium: 240, vitaminD: 3,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'pizza-white',
    name: 'Pizza blanche',
    category: 'pizza',
    portionG: 130,
    kcal: 285, protein: 11, fat: 13, carbs: 30,
    fiber: 2, sugar: 2, sodium: 620,
    calcium: 200, iron: 1.8, potassium: 130, vitaminD: 5,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian']
  },
  {
    id: 'calzone',
    name: 'Calzone',
    category: 'pizza',
    portionG: 280,
    kcal: 290, protein: 14, fat: 13, carbs: 29,
    fiber: 2, sugar: 3, sodium: 700,
    calcium: 160, iron: 2.4, potassium: 200, vitaminD: 5,
    allergens: ['gluten', 'lait'],
    tags: ['high-protein']
  },
  {
    id: 'stromboli',
    name: 'Stromboli',
    category: 'pizza',
    portionG: 250,
    kcal: 280, protein: 13, fat: 12, carbs: 30,
    fiber: 2, sugar: 3, sodium: 720,
    calcium: 150, iron: 2.3, potassium: 180, vitaminD: 4,
    allergens: ['gluten', 'lait'],
    tags: []
  },

  // ============ SANDWICHES ============
  {
    id: 'turkey-sandwich',
    name: 'Turkey sandwich',
    category: 'sandwiches',
    portionG: 230,
    kcal: 220, protein: 18, fat: 6, carbs: 25,
    fiber: 2, sugar: 3, sodium: 700,
    calcium: 75, iron: 2.0, potassium: 220, vitaminD: 2,
    allergens: ['gluten'],
    tags: ['halal', 'high-protein'],
    notes: 'Plus maigre'
  },
  {
    id: 'ham-sandwich',
    name: 'Ham sandwich',
    category: 'sandwiches',
    portionG: 230,
    kcal: 240, protein: 14, fat: 9, carbs: 25,
    fiber: 2, sugar: 4, sodium: 880,
    calcium: 80, iron: 2.0, potassium: 215, vitaminD: 5,
    allergens: ['gluten'],
    tags: []
  },
  {
    id: 'club-sandwich',
    name: 'Club sandwich',
    category: 'sandwiches',
    portionG: 280,
    kcal: 260, protein: 15, fat: 12, carbs: 23,
    fiber: 2, sugar: 3, sodium: 770,
    calcium: 90, iron: 2.0, potassium: 240, vitaminD: 6,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['high-protein'],
    notes: 'Contient souvent du bacon'
  },
  {
    id: 'blt-sandwich',
    name: 'BLT sandwich',
    category: 'sandwiches',
    portionG: 200,
    kcal: 270, protein: 11, fat: 15, carbs: 24,
    fiber: 2, sugar: 4, sodium: 760,
    calcium: 60, iron: 1.8, potassium: 230, vitaminD: 5,
    allergens: ['gluten'],
    tags: []
  },
  {
    id: 'grilled-cheese',
    name: 'Grilled cheese',
    category: 'sandwiches',
    portionG: 130,
    kcal: 291, protein: 12, fat: 16, carbs: 27,
    fiber: 1, sugar: 4, sodium: 720,
    calcium: 320, iron: 1.6, potassium: 100, vitaminD: 10,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian'],
    notes: 'Gras saturés ++'
  },
  {
    id: 'tuna-melt',
    name: 'Tuna melt',
    category: 'sandwiches',
    portionG: 220,
    kcal: 285, protein: 18, fat: 14, carbs: 22,
    fiber: 1, sugar: 3, sodium: 690,
    calcium: 200, iron: 1.7, potassium: 240, vitaminD: 35,
    allergens: ['gluten', 'lait', 'poisson'],
    tags: ['high-protein']
  },
  {
    id: 'philly-cheesesteak',
    name: 'Philly cheesesteak',
    category: 'sandwiches',
    portionG: 300,
    kcal: 280, protein: 17, fat: 13, carbs: 24,
    fiber: 2, sugar: 3, sodium: 760,
    calcium: 170, iron: 2.6, potassium: 280, vitaminD: 4,
    allergens: ['gluten', 'lait'],
    tags: ['high-protein']
  },
  {
    id: 'panini',
    name: 'Panini',
    category: 'sandwiches',
    portionG: 220,
    kcal: 275, protein: 14, fat: 12, carbs: 28,
    fiber: 2, sugar: 3, sodium: 680,
    calcium: 150, iron: 2.0, potassium: 200, vitaminD: 4,
    allergens: ['gluten', 'lait'],
    tags: []
  },
  {
    id: 'wrap-veggie',
    name: 'Wrap végétarien',
    category: 'sandwiches',
    portionG: 220,
    kcal: 215, protein: 8, fat: 9, carbs: 28,
    fiber: 4, sugar: 3, sodium: 540,
    calcium: 110, iron: 1.8, potassium: 280, vitaminD: 2,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian']
  },
  {
    id: 'sub-italian',
    name: 'Sub italien',
    category: 'sandwiches',
    portionG: 280,
    kcal: 260, protein: 13, fat: 11, carbs: 27,
    fiber: 2, sugar: 4, sodium: 920,
    calcium: 110, iron: 2.2, potassium: 230, vitaminD: 4,
    allergens: ['gluten', 'lait'],
    tags: []
  },
  {
    id: 'reuben',
    name: 'Reuben',
    category: 'sandwiches',
    portionG: 260,
    kcal: 310, protein: 16, fat: 17, carbs: 22,
    fiber: 3, sugar: 4, sodium: 1050,
    calcium: 220, iron: 2.5, potassium: 270, vitaminD: 6,
    allergens: ['gluten', 'lait'],
    tags: ['high-protein']
  },
  {
    id: 'chicken-caesar-wrap',
    name: 'Chicken Caesar wrap',
    category: 'sandwiches',
    portionG: 250,
    kcal: 245, protein: 16, fat: 11, carbs: 22,
    fiber: 2, sugar: 2, sodium: 620,
    calcium: 120, iron: 1.8, potassium: 240, vitaminD: 4,
    allergens: ['gluten', 'lait', 'œuf', 'poisson'],
    tags: ['halal', 'high-protein']
  },

  // ============ SALADES & HEALTHY ============
  {
    id: 'caesar-salad',
    name: 'Caesar salad',
    category: 'salads-healthy',
    portionG: 250,
    kcal: 190, protein: 7, fat: 15, carbs: 8,
    fiber: 2, sugar: 2, sodium: 510,
    calcium: 130, iron: 1.5, potassium: 280, vitaminD: 5,
    allergens: ['lait', 'œuf', 'gluten', 'poisson'],
    tags: ['vegetarian'],
    notes: 'Sauce calorique'
  },
  {
    id: 'greek-salad',
    name: 'Greek salad',
    category: 'salads-healthy',
    portionG: 250,
    kcal: 130, protein: 5, fat: 9, carbs: 8,
    fiber: 3, sugar: 5, sodium: 470,
    calcium: 130, iron: 1.0, potassium: 320, vitaminD: 2,
    allergens: ['lait'],
    tags: ['vegetarian', 'halal', 'gluten-free', 'low-carb']
  },
  {
    id: 'cobb-salad',
    name: 'Cobb salad',
    category: 'salads-healthy',
    portionG: 300,
    kcal: 220, protein: 14, fat: 16, carbs: 7,
    fiber: 3, sugar: 3, sodium: 580,
    calcium: 140, iron: 1.6, potassium: 380, vitaminD: 12,
    allergens: ['œuf', 'lait'],
    tags: ['gluten-free', 'high-protein', 'low-carb'],
    notes: 'Œufs + fromage'
  },
  {
    id: 'garden-salad',
    name: 'Garden salad',
    category: 'salads-healthy',
    portionG: 200,
    kcal: 85, protein: 3, fat: 5, carbs: 8,
    fiber: 3, sugar: 4, sodium: 220,
    calcium: 60, iron: 1.0, potassium: 320, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free', 'low-carb']
  },
  {
    id: 'quinoa-bowl',
    name: 'Quinoa bowl',
    category: 'salads-healthy',
    portionG: 320,
    kcal: 170, protein: 7, fat: 6, carbs: 22,
    fiber: 4, sugar: 3, sodium: 230,
    calcium: 50, iron: 2.0, potassium: 280, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'gluten-free', 'dairy-free']
  },
  {
    id: 'rice-bowl',
    name: 'Rice bowl',
    category: 'salads-healthy',
    portionG: 350,
    kcal: 140, protein: 4, fat: 1, carbs: 30,
    fiber: 2, sugar: 1, sodium: 250,
    calcium: 20, iron: 1.2, potassium: 130, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'gluten-free', 'dairy-free', 'high-carb'],
    notes: 'Base glucidique'
  },
  {
    id: 'poke-bowl',
    name: 'Poke bowl',
    category: 'salads-healthy',
    portionG: 380,
    kcal: 160, protein: 14, fat: 4, carbs: 18,
    fiber: 2, sugar: 3, sodium: 410,
    calcium: 30, iron: 1.1, potassium: 320, vitaminD: 15,
    allergens: ['poisson', 'soja', 'sésame'],
    tags: ['high-protein'],
    notes: 'Oméga-3 ++'
  },
  {
    id: 'buddha-bowl',
    name: 'Buddha bowl',
    category: 'salads-healthy',
    portionG: 380,
    kcal: 165, protein: 7, fat: 6, carbs: 22,
    fiber: 5, sugar: 4, sodium: 280,
    calcium: 60, iron: 2.2, potassium: 380, vitaminD: 0,
    allergens: ['sésame'],
    tags: ['vegetarian', 'vegan', 'halal', 'gluten-free', 'dairy-free']
  },
  {
    id: 'grain-bowl',
    name: 'Grain bowl',
    category: 'salads-healthy',
    portionG: 350,
    kcal: 180, protein: 8, fat: 6, carbs: 24,
    fiber: 4, sugar: 2, sodium: 320,
    calcium: 50, iron: 2.0, potassium: 280, vitaminD: 0,
    allergens: ['gluten'],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free']
  },
  {
    id: 'pasta-salad',
    name: 'Salade de pâtes',
    category: 'salads-healthy',
    portionG: 250,
    kcal: 195, protein: 5, fat: 10, carbs: 22,
    fiber: 2, sugar: 3, sodium: 380,
    calcium: 40, iron: 1.2, potassium: 130, vitaminD: 0,
    allergens: ['gluten'],
    tags: ['vegetarian']
  },
  {
    id: 'tuna-salad',
    name: 'Salade de thon',
    category: 'salads-healthy',
    portionG: 220,
    kcal: 187, protein: 16, fat: 10, carbs: 7,
    fiber: 1, sugar: 2, sodium: 460,
    calcium: 30, iron: 1.1, potassium: 270, vitaminD: 40,
    allergens: ['poisson', 'œuf'],
    tags: ['gluten-free', 'dairy-free', 'high-protein', 'low-carb']
  },
  {
    id: 'fruit-salad',
    name: 'Salade de fruits',
    category: 'salads-healthy',
    portionG: 200,
    kcal: 65, protein: 0.7, fat: 0.2, carbs: 16,
    fiber: 2, sugar: 13, sodium: 3,
    calcium: 15, iron: 0.3, potassium: 200, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },

  // ============ MEXICAIN ============
  {
    id: 'burrito',
    name: 'Burrito',
    category: 'mexican',
    portionG: 320,
    kcal: 210, protein: 9, fat: 7, carbs: 28,
    fiber: 3, sugar: 2, sodium: 530,
    calcium: 90, iron: 2.1, potassium: 250, vitaminD: 3,
    allergens: ['gluten', 'lait'],
    tags: ['high-carb']
  },
  {
    id: 'taco',
    name: 'Taco',
    category: 'mexican',
    portionG: 100,
    kcal: 226, protein: 11, fat: 13, carbs: 18,
    fiber: 3, sugar: 1, sodium: 397,
    calcium: 110, iron: 1.6, potassium: 190, vitaminD: 4,
    allergens: ['gluten', 'lait'],
    tags: []
  },
  {
    id: 'quesadilla',
    name: 'Quesadilla',
    category: 'mexican',
    portionG: 200,
    kcal: 290, protein: 13, fat: 17, carbs: 22,
    fiber: 2, sugar: 2, sodium: 620,
    calcium: 270, iron: 1.5, potassium: 130, vitaminD: 9,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian'],
    notes: 'Fromage ++'
  },
  {
    id: 'nachos',
    name: 'Nachos',
    category: 'mexican',
    portionG: 200,
    kcal: 345, protein: 9, fat: 19, carbs: 36,
    fiber: 4, sugar: 2, sodium: 720,
    calcium: 180, iron: 1.4, potassium: 260, vitaminD: 5,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian']
  },
  {
    id: 'enchilada',
    name: 'Enchilada',
    category: 'mexican',
    portionG: 220,
    kcal: 215, protein: 11, fat: 10, carbs: 22,
    fiber: 3, sugar: 4, sodium: 580,
    calcium: 150, iron: 1.7, potassium: 270, vitaminD: 4,
    allergens: ['gluten', 'lait'],
    tags: []
  },
  {
    id: 'fajitas',
    name: 'Fajitas',
    category: 'mexican',
    portionG: 300,
    kcal: 195, protein: 14, fat: 8, carbs: 18,
    fiber: 3, sugar: 4, sodium: 500,
    calcium: 80, iron: 2.2, potassium: 340, vitaminD: 3,
    allergens: ['gluten'],
    tags: ['halal', 'high-protein']
  },
  {
    id: 'rice-beans',
    name: 'Rice & beans',
    category: 'mexican',
    portionG: 250,
    kcal: 135, protein: 6, fat: 1, carbs: 26,
    fiber: 4, sugar: 1, sodium: 320,
    calcium: 30, iron: 1.6, potassium: 240, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'gluten-free', 'dairy-free', 'high-carb']
  },
  {
    id: 'chips-salsa',
    name: 'Chips & salsa',
    category: 'mexican',
    portionG: 100,
    kcal: 420, protein: 6, fat: 22, carbs: 50,
    fiber: 5, sugar: 3, sodium: 480,
    calcium: 90, iron: 1.4, potassium: 270, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'gluten-free', 'dairy-free']
  },
  {
    id: 'guacamole',
    name: 'Guacamole',
    category: 'mexican',
    portionG: 60,
    kcal: 156, protein: 2, fat: 14, carbs: 8,
    fiber: 7, sugar: 1, sodium: 320,
    calcium: 13, iron: 0.6, potassium: 485, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free', 'low-carb']
  },
  {
    id: 'carnitas',
    name: 'Carnitas',
    category: 'mexican',
    portionG: 150,
    kcal: 245, protein: 22, fat: 17, carbs: 1,
    fiber: 0, sugar: 0, sodium: 530,
    calcium: 15, iron: 1.6, potassium: 350, vitaminD: 12,
    allergens: [],
    tags: ['gluten-free', 'dairy-free', 'high-protein', 'low-carb']
  },

  // ============ ASIATIQUE ============
  {
    id: 'fried-rice',
    name: 'Riz frit',
    category: 'asian',
    portionG: 250,
    kcal: 174, protein: 5, fat: 5, carbs: 26,
    fiber: 1, sugar: 1, sodium: 480,
    calcium: 20, iron: 1.2, potassium: 100, vitaminD: 3,
    allergens: ['œuf', 'soja', 'gluten'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'lo-mein',
    name: 'Lo mein',
    category: 'asian',
    portionG: 280,
    kcal: 165, protein: 6, fat: 5, carbs: 24,
    fiber: 2, sugar: 3, sodium: 530,
    calcium: 25, iron: 1.4, potassium: 160, vitaminD: 0,
    allergens: ['gluten', 'soja', 'sésame'],
    tags: ['high-carb']
  },
  {
    id: 'chow-mein',
    name: 'Nouilles sautées',
    category: 'asian',
    portionG: 280,
    kcal: 195, protein: 7, fat: 8, carbs: 24,
    fiber: 2, sugar: 2, sodium: 580,
    calcium: 30, iron: 1.6, potassium: 180, vitaminD: 0,
    allergens: ['gluten', 'soja', 'sésame'],
    tags: []
  },
  {
    id: 'pad-thai',
    name: 'Pad Thai',
    category: 'asian',
    portionG: 300,
    kcal: 190, protein: 8, fat: 8, carbs: 22,
    fiber: 2, sugar: 6, sodium: 540,
    calcium: 40, iron: 1.3, potassium: 200, vitaminD: 3,
    allergens: ['arachide', 'œuf', 'soja', 'fruits-de-mer'],
    tags: [],
    notes: 'Sauce sucrée'
  },
  {
    id: 'ramen',
    name: 'Ramen',
    category: 'asian',
    portionG: 450,
    kcal: 188, protein: 6, fat: 7, carbs: 25,
    fiber: 1, sugar: 1, sodium: 880,
    calcium: 18, iron: 1.5, potassium: 90, vitaminD: 2,
    allergens: ['gluten', 'soja', 'œuf'],
    tags: ['high-carb'],
    notes: 'Sodium ++'
  },
  {
    id: 'udon',
    name: 'Udon',
    category: 'asian',
    portionG: 400,
    kcal: 165, protein: 6, fat: 1, carbs: 33,
    fiber: 2, sugar: 1, sodium: 540,
    calcium: 15, iron: 0.8, potassium: 70, vitaminD: 0,
    allergens: ['gluten', 'soja'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'sushi',
    name: 'Sushi (assortiment)',
    category: 'asian',
    portionG: 200,
    kcal: 143, protein: 7, fat: 1, carbs: 28,
    fiber: 1, sugar: 4, sodium: 380,
    calcium: 12, iron: 0.7, potassium: 90, vitaminD: 18,
    allergens: ['poisson', 'soja', 'fruits-de-mer'],
    tags: ['dairy-free', 'high-carb'],
    notes: 'Peu gras'
  },
  {
    id: 'california-rolls',
    name: 'California rolls',
    category: 'asian',
    portionG: 200,
    kcal: 155, protein: 5, fat: 4, carbs: 25,
    fiber: 2, sugar: 4, sodium: 410,
    calcium: 20, iron: 0.8, potassium: 130, vitaminD: 0,
    allergens: ['poisson', 'fruits-de-mer', 'soja', 'sésame'],
    tags: ['dairy-free']
  },
  {
    id: 'teriyaki-chicken',
    name: 'Teriyaki chicken',
    category: 'asian',
    portionG: 200,
    kcal: 190, protein: 19, fat: 6, carbs: 15,
    fiber: 0, sugar: 12, sodium: 690,
    calcium: 15, iron: 1.0, potassium: 290, vitaminD: 3,
    allergens: ['soja', 'gluten'],
    tags: ['halal', 'dairy-free', 'high-protein']
  },
  {
    id: 'orange-chicken',
    name: 'Orange chicken',
    category: 'asian',
    portionG: 200,
    kcal: 245, protein: 13, fat: 11, carbs: 24,
    fiber: 0, sugar: 14, sodium: 620,
    calcium: 18, iron: 1.0, potassium: 220, vitaminD: 3,
    allergens: ['gluten', 'soja', 'œuf'],
    tags: ['dairy-free', 'high-protein']
  },
  {
    id: 'general-tso',
    name: 'General Tso',
    category: 'asian',
    portionG: 200,
    kcal: 290, protein: 13, fat: 16, carbs: 23,
    fiber: 1, sugar: 12, sodium: 730,
    calcium: 22, iron: 1.2, potassium: 230, vitaminD: 3,
    allergens: ['gluten', 'soja', 'œuf'],
    tags: ['dairy-free']
  },
  {
    id: 'dumplings',
    name: 'Dumplings',
    category: 'asian',
    portionG: 150,
    kcal: 220, protein: 8, fat: 8, carbs: 28,
    fiber: 1, sugar: 1, sodium: 540,
    calcium: 25, iron: 1.5, potassium: 130, vitaminD: 3,
    allergens: ['gluten', 'soja', 'sésame'],
    tags: ['dairy-free']
  },
  {
    id: 'egg-rolls',
    name: 'Egg rolls',
    category: 'asian',
    portionG: 90,
    kcal: 230, protein: 7, fat: 11, carbs: 25,
    fiber: 2, sugar: 2, sodium: 510,
    calcium: 30, iron: 1.3, potassium: 170, vitaminD: 4,
    allergens: ['gluten', 'œuf', 'soja'],
    tags: []
  },
  {
    id: 'bibimbap',
    name: 'Bibimbap',
    category: 'asian',
    portionG: 400,
    kcal: 145, protein: 7, fat: 4, carbs: 20,
    fiber: 2, sugar: 2, sodium: 410,
    calcium: 30, iron: 1.6, potassium: 220, vitaminD: 5,
    allergens: ['œuf', 'soja', 'sésame'],
    tags: ['dairy-free']
  },
  {
    id: 'korean-bbq',
    name: 'Korean BBQ',
    category: 'asian',
    portionG: 250,
    kcal: 245, protein: 21, fat: 14, carbs: 8,
    fiber: 0, sugar: 6, sodium: 720,
    calcium: 25, iron: 2.4, potassium: 320, vitaminD: 4,
    allergens: ['soja', 'sésame', 'gluten'],
    tags: ['dairy-free', 'high-protein']
  },
  {
    id: 'pho',
    name: 'Pho',
    category: 'asian',
    portionG: 500,
    kcal: 90, protein: 6, fat: 2, carbs: 12,
    fiber: 1, sugar: 1, sodium: 480,
    calcium: 18, iron: 0.9, potassium: 150, vitaminD: 1,
    allergens: ['soja'],
    tags: ['dairy-free']
  },
  {
    id: 'thai-curry',
    name: 'Curry thaï',
    category: 'asian',
    portionG: 300,
    kcal: 180, protein: 7, fat: 11, carbs: 13,
    fiber: 2, sugar: 4, sodium: 520,
    calcium: 30, iron: 1.4, potassium: 280, vitaminD: 1,
    allergens: ['fruits-de-mer', 'soja'],
    tags: ['gluten-free', 'dairy-free']
  },
  {
    id: 'banh-mi',
    name: 'Banh mi',
    category: 'asian',
    portionG: 250,
    kcal: 225, protein: 11, fat: 8, carbs: 28,
    fiber: 2, sugar: 4, sodium: 620,
    calcium: 35, iron: 2.1, potassium: 220, vitaminD: 3,
    allergens: ['gluten', 'soja', 'œuf'],
    tags: []
  },

  // ============ ITALIEN ============
  {
    id: 'spaghetti-bolognese',
    name: 'Spaghetti bolognaise',
    category: 'italian',
    portionG: 350,
    kcal: 158, protein: 8, fat: 5, carbs: 21,
    fiber: 2, sugar: 3, sodium: 320,
    calcium: 30, iron: 1.6, potassium: 220, vitaminD: 2,
    allergens: ['gluten'],
    tags: ['dairy-free', 'high-carb']
  },
  {
    id: 'lasagna',
    name: 'Lasagnes',
    category: 'italian',
    portionG: 300,
    kcal: 132, protein: 8, fat: 6, carbs: 12,
    fiber: 1, sugar: 3, sodium: 380,
    calcium: 130, iron: 1.2, potassium: 200, vitaminD: 3,
    allergens: ['gluten', 'lait', 'œuf'],
    tags: []
  },
  {
    id: 'alfredo-pasta',
    name: 'Alfredo pasta',
    category: 'italian',
    portionG: 300,
    kcal: 235, protein: 8, fat: 12, carbs: 25,
    fiber: 1, sugar: 2, sodium: 480,
    calcium: 150, iron: 1.0, potassium: 110, vitaminD: 5,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian']
  },
  {
    id: 'penne-vodka',
    name: 'Penne vodka',
    category: 'italian',
    portionG: 300,
    kcal: 210, protein: 7, fat: 9, carbs: 26,
    fiber: 2, sugar: 4, sodium: 420,
    calcium: 90, iron: 1.3, potassium: 200, vitaminD: 3,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian']
  },
  {
    id: 'mac-cheese',
    name: 'Mac & cheese',
    category: 'italian',
    portionG: 250,
    kcal: 164, protein: 7, fat: 7, carbs: 18,
    fiber: 1, sugar: 2, sodium: 410,
    calcium: 150, iron: 0.8, potassium: 90, vitaminD: 4,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian'],
    notes: 'Comfort food'
  },
  {
    id: 'ravioli',
    name: 'Ravioli',
    category: 'italian',
    portionG: 250,
    kcal: 220, protein: 9, fat: 7, carbs: 30,
    fiber: 2, sugar: 3, sodium: 430,
    calcium: 80, iron: 1.6, potassium: 170, vitaminD: 4,
    allergens: ['gluten', 'lait', 'œuf'],
    tags: ['vegetarian']
  },
  {
    id: 'meatballs',
    name: 'Meatballs',
    category: 'italian',
    portionG: 150,
    kcal: 240, protein: 18, fat: 16, carbs: 6,
    fiber: 1, sugar: 2, sodium: 530,
    calcium: 50, iron: 2.1, potassium: 290, vitaminD: 4,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['high-protein']
  },
  {
    id: 'garlic-bread',
    name: 'Garlic bread',
    category: 'italian',
    portionG: 80,
    kcal: 350, protein: 8, fat: 18, carbs: 38,
    fiber: 2, sugar: 2, sodium: 590,
    calcium: 80, iron: 2.2, potassium: 110, vitaminD: 2,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian', 'high-carb']
  },

  // ============ COMFORT FOOD US ============
  {
    id: 'meatloaf',
    name: 'Meatloaf',
    category: 'comfort-us',
    portionG: 180,
    kcal: 235, protein: 17, fat: 14, carbs: 9,
    fiber: 1, sugar: 4, sodium: 520,
    calcium: 40, iron: 2.3, potassium: 290, vitaminD: 5,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['high-protein']
  },
  {
    id: 'fried-chicken',
    name: 'Fried chicken',
    category: 'comfort-us',
    portionG: 180,
    kcal: 320, protein: 25, fat: 20, carbs: 8,
    fiber: 0, sugar: 0, sodium: 590,
    calcium: 22, iron: 1.5, potassium: 240, vitaminD: 4,
    allergens: ['gluten', 'œuf'],
    tags: ['halal', 'high-protein'],
    notes: 'Panure + friture'
  },
  {
    id: 'mashed-potatoes',
    name: 'Mashed potatoes',
    category: 'comfort-us',
    portionG: 180,
    kcal: 113, protein: 2, fat: 4, carbs: 17,
    fiber: 2, sugar: 1, sodium: 320,
    calcium: 25, iron: 0.3, potassium: 320, vitaminD: 2,
    allergens: ['lait'],
    tags: ['vegetarian', 'halal', 'gluten-free']
  },
  {
    id: 'gravy',
    name: 'Gravy',
    category: 'comfort-us',
    portionG: 60,
    kcal: 80, protein: 2, fat: 5, carbs: 7,
    fiber: 0, sugar: 1, sodium: 670,
    calcium: 8, iron: 0.4, potassium: 60, vitaminD: 1,
    allergens: ['gluten', 'lait'],
    tags: []
  },
  {
    id: 'pulled-pork',
    name: 'Pulled pork',
    category: 'comfort-us',
    portionG: 180,
    kcal: 250, protein: 24, fat: 16, carbs: 3,
    fiber: 0, sugar: 2, sodium: 510,
    calcium: 15, iron: 1.6, potassium: 360, vitaminD: 12,
    allergens: [],
    tags: ['gluten-free', 'dairy-free', 'high-protein', 'low-carb'],
    notes: 'Protéines ++'
  },
  {
    id: 'bbq-ribs',
    name: 'BBQ ribs',
    category: 'comfort-us',
    portionG: 250,
    kcal: 290, protein: 22, fat: 20, carbs: 8,
    fiber: 0, sugar: 7, sodium: 620,
    calcium: 30, iron: 1.8, potassium: 320, vitaminD: 10,
    allergens: [],
    tags: ['gluten-free', 'dairy-free', 'high-protein']
  },
  {
    id: 'chili',
    name: 'Chili con carne',
    category: 'comfort-us',
    portionG: 300,
    kcal: 140, protein: 9, fat: 6, carbs: 12,
    fiber: 4, sugar: 3, sodium: 460,
    calcium: 30, iron: 1.8, potassium: 320, vitaminD: 2,
    allergens: [],
    tags: ['gluten-free', 'dairy-free']
  },
  {
    id: 'chicken-pot-pie',
    name: 'Chicken pot pie',
    category: 'comfort-us',
    portionG: 250,
    kcal: 260, protein: 9, fat: 16, carbs: 22,
    fiber: 2, sugar: 2, sodium: 580,
    calcium: 35, iron: 1.8, potassium: 200, vitaminD: 5,
    allergens: ['gluten', 'lait', 'œuf'],
    tags: []
  },

  // ============ INTERNATIONAL ============
  {
    id: 'indian-curry',
    name: 'Curry indien',
    category: 'international',
    portionG: 300,
    kcal: 195, protein: 8, fat: 12, carbs: 14,
    fiber: 3, sugar: 4, sodium: 510,
    calcium: 60, iron: 1.8, potassium: 320, vitaminD: 2,
    allergens: ['lait'],
    tags: ['gluten-free']
  },
  {
    id: 'butter-chicken',
    name: 'Butter chicken',
    category: 'international',
    portionG: 280,
    kcal: 230, protein: 15, fat: 15, carbs: 7,
    fiber: 1, sugar: 4, sodium: 520,
    calcium: 75, iron: 1.4, potassium: 280, vitaminD: 4,
    allergens: ['lait'],
    tags: ['halal', 'gluten-free', 'high-protein'],
    notes: 'Sauce crémeuse'
  },
  {
    id: 'tikka-masala',
    name: 'Chicken tikka masala',
    category: 'international',
    portionG: 280,
    kcal: 215, protein: 14, fat: 13, carbs: 8,
    fiber: 1, sugar: 4, sodium: 540,
    calcium: 80, iron: 1.5, potassium: 290, vitaminD: 3,
    allergens: ['lait'],
    tags: ['halal', 'gluten-free']
  },
  {
    id: 'basmati-rice',
    name: 'Riz basmati',
    category: 'international',
    portionG: 200,
    kcal: 121, protein: 3, fat: 0.4, carbs: 26,
    fiber: 0.4, sugar: 0, sodium: 1,
    calcium: 10, iron: 0.4, potassium: 35, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free', 'high-carb']
  },
  {
    id: 'falafel',
    name: 'Falafel',
    category: 'international',
    portionG: 120,
    kcal: 333, protein: 13, fat: 18, carbs: 31,
    fiber: 5, sugar: 3, sodium: 585,
    calcium: 54, iron: 3.4, potassium: 585, vitaminD: 0,
    allergens: ['gluten', 'sésame'],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'dairy-free'],
    notes: 'Fibres ++'
  },
  {
    id: 'shawarma',
    name: 'Shawarma',
    category: 'international',
    portionG: 250,
    kcal: 220, protein: 19, fat: 13, carbs: 8,
    fiber: 1, sugar: 2, sodium: 540,
    calcium: 40, iron: 1.8, potassium: 280, vitaminD: 4,
    allergens: ['gluten', 'sésame'],
    tags: ['halal', 'high-protein']
  },
  {
    id: 'gyro',
    name: 'Gyro',
    category: 'international',
    portionG: 250,
    kcal: 245, protein: 18, fat: 14, carbs: 12,
    fiber: 1, sugar: 2, sodium: 620,
    calcium: 80, iron: 2.0, potassium: 290, vitaminD: 4,
    allergens: ['gluten', 'lait'],
    tags: ['high-protein']
  },
  {
    id: 'hummus',
    name: 'Hummus',
    category: 'international',
    portionG: 60,
    kcal: 166, protein: 8, fat: 10, carbs: 14,
    fiber: 6, sugar: 0, sodium: 379,
    calcium: 38, iron: 2.4, potassium: 228, vitaminD: 0,
    allergens: ['sésame'],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'couscous',
    name: 'Couscous',
    category: 'international',
    portionG: 200,
    kcal: 112, protein: 4, fat: 0.2, carbs: 23,
    fiber: 1, sugar: 0, sodium: 5,
    calcium: 8, iron: 0.4, potassium: 60, vitaminD: 0,
    allergens: ['gluten'],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free', 'high-carb']
  },
  {
    id: 'jerk-chicken',
    name: 'Jerk chicken',
    category: 'international',
    portionG: 200,
    kcal: 230, protein: 24, fat: 12, carbs: 5,
    fiber: 1, sugar: 2, sodium: 580,
    calcium: 25, iron: 1.6, potassium: 320, vitaminD: 4,
    allergens: [],
    tags: ['halal', 'gluten-free', 'dairy-free', 'high-protein', 'low-carb']
  },
  {
    id: 'empanadas',
    name: 'Empanadas',
    category: 'international',
    portionG: 130,
    kcal: 290, protein: 10, fat: 16, carbs: 26,
    fiber: 2, sugar: 2, sodium: 460,
    calcium: 45, iron: 2.0, potassium: 220, vitaminD: 4,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: []
  },

  // ============ VÉGÉ & VEGAN ============
  {
    id: 'grilled-tofu',
    name: 'Tofu grillé',
    category: 'veg-vegan',
    portionG: 150,
    kcal: 76, protein: 8, fat: 4, carbs: 2,
    fiber: 1, sugar: 1, sodium: 12,
    calcium: 350, iron: 2.7, potassium: 121, vitaminD: 0,
    allergens: ['soja'],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free', 'high-protein', 'low-carb'],
    notes: 'Faible en calories'
  },
  {
    id: 'tempeh',
    name: 'Tempeh',
    category: 'veg-vegan',
    portionG: 120,
    kcal: 192, protein: 20, fat: 11, carbs: 8,
    fiber: 1, sugar: 0, sodium: 9,
    calcium: 111, iron: 2.7, potassium: 412, vitaminD: 0,
    allergens: ['soja'],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free', 'high-protein']
  },
  {
    id: 'lentils',
    name: 'Lentilles',
    category: 'veg-vegan',
    portionG: 200,
    kcal: 116, protein: 9, fat: 0.4, carbs: 20,
    fiber: 8, sugar: 2, sodium: 2,
    calcium: 19, iron: 3.3, potassium: 369, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free', 'high-protein']
  },
  {
    id: 'vegan-burger',
    name: 'Vegan burger',
    category: 'veg-vegan',
    portionG: 220,
    kcal: 180, protein: 17, fat: 6, carbs: 15,
    fiber: 4, sugar: 2, sodium: 480,
    calcium: 90, iron: 3.0, potassium: 380, vitaminD: 0,
    allergens: ['soja', 'gluten'],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free', 'high-protein']
  },
  {
    id: 'vegan-pizza',
    name: 'Vegan pizza',
    category: 'veg-vegan',
    portionG: 140,
    kcal: 220, protein: 8, fat: 7, carbs: 32,
    fiber: 3, sugar: 4, sodium: 540,
    calcium: 80, iron: 1.8, potassium: 250, vitaminD: 0,
    allergens: ['gluten', 'soja'],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free', 'high-carb']
  },
  {
    id: 'vegan-salad',
    name: 'Salade vegan',
    category: 'veg-vegan',
    portionG: 280,
    kcal: 110, protein: 5, fat: 5, carbs: 12,
    fiber: 4, sugar: 4, sodium: 220,
    calcium: 60, iron: 1.6, potassium: 360, vitaminD: 0,
    allergens: ['sésame'],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'plant-based-nuggets',
    name: 'Plant-based nuggets',
    category: 'veg-vegan',
    portionG: 130,
    kcal: 235, protein: 14, fat: 11, carbs: 18,
    fiber: 3, sugar: 1, sodium: 530,
    calcium: 60, iron: 2.4, potassium: 220, vitaminD: 0,
    allergens: ['soja', 'gluten'],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free', 'high-protein']
  },
  {
    id: 'vegan-burrito',
    name: 'Vegan burrito',
    category: 'veg-vegan',
    portionG: 320,
    kcal: 195, protein: 8, fat: 6, carbs: 28,
    fiber: 5, sugar: 2, sodium: 480,
    calcium: 80, iron: 2.4, potassium: 320, vitaminD: 0,
    allergens: ['gluten', 'soja'],
    tags: ['vegetarian', 'vegan', 'halal', 'dairy-free', 'high-carb']
  },
  {
    id: 'vegan-soup',
    name: 'Soupe vegan (légumes)',
    category: 'veg-vegan',
    portionG: 350,
    kcal: 55, protein: 2, fat: 1.5, carbs: 9,
    fiber: 2, sugar: 3, sodium: 380,
    calcium: 25, iron: 0.7, potassium: 240, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },

  // ============ DESSERTS ============
  {
    id: 'cookies',
    name: 'Cookies',
    category: 'desserts',
    portionG: 35,
    kcal: 488, protein: 5, fat: 24, carbs: 65,
    fiber: 2, sugar: 38, sodium: 380,
    calcium: 30, iron: 2.0, potassium: 130, vitaminD: 5,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['vegetarian', 'high-carb'],
    notes: 'Très énergétique'
  },
  {
    id: 'brownies',
    name: 'Brownies',
    category: 'desserts',
    portionG: 60,
    kcal: 466, protein: 5, fat: 24, carbs: 60,
    fiber: 3, sugar: 42, sodium: 290,
    calcium: 30, iron: 2.6, potassium: 200, vitaminD: 5,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['vegetarian', 'high-carb'],
    notes: 'Sucre ++'
  },
  {
    id: 'ice-cream',
    name: 'Ice cream',
    category: 'desserts',
    portionG: 100,
    kcal: 207, protein: 3.5, fat: 11, carbs: 24,
    fiber: 0.7, sugar: 21, sodium: 80,
    calcium: 128, iron: 0.1, potassium: 199, vitaminD: 5,
    allergens: ['lait', 'œuf'],
    tags: ['vegetarian']
  },
  {
    id: 'cheesecake',
    name: 'Cheesecake',
    category: 'desserts',
    portionG: 120,
    kcal: 321, protein: 6, fat: 22, carbs: 26,
    fiber: 0.4, sugar: 22, sodium: 250,
    calcium: 50, iron: 0.6, potassium: 100, vitaminD: 7,
    allergens: ['gluten', 'lait', 'œuf'],
    tags: ['vegetarian']
  },
  {
    id: 'cupcake',
    name: 'Cupcake',
    category: 'desserts',
    portionG: 60,
    kcal: 370, protein: 4, fat: 16, carbs: 53,
    fiber: 1, sugar: 35, sodium: 290,
    calcium: 30, iron: 1.4, potassium: 100, vitaminD: 4,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'apple-pie',
    name: 'Apple pie',
    category: 'desserts',
    portionG: 130,
    kcal: 265, protein: 2, fat: 12, carbs: 38,
    fiber: 2, sugar: 18, sodium: 200,
    calcium: 12, iron: 0.7, potassium: 80, vitaminD: 2,
    allergens: ['gluten', 'lait'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'chocolate-cake',
    name: 'Chocolate cake',
    category: 'desserts',
    portionG: 100,
    kcal: 371, protein: 5, fat: 16, carbs: 53,
    fiber: 2, sugar: 38, sodium: 320,
    calcium: 55, iron: 2.4, potassium: 180, vitaminD: 4,
    allergens: ['gluten', 'œuf', 'lait'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'banana-pudding',
    name: 'Banana pudding',
    category: 'desserts',
    portionG: 150,
    kcal: 185, protein: 3, fat: 7, carbs: 28,
    fiber: 1, sugar: 22, sodium: 140,
    calcium: 70, iron: 0.4, potassium: 220, vitaminD: 4,
    allergens: ['lait', 'œuf', 'gluten'],
    tags: ['vegetarian']
  },
  {
    id: 'rice-krispie-treats',
    name: 'Rice Krispie treats',
    category: 'desserts',
    portionG: 30,
    kcal: 400, protein: 3, fat: 7, carbs: 81,
    fiber: 0.5, sugar: 45, sodium: 370,
    calcium: 10, iron: 4.0, potassium: 40, vitaminD: 0,
    allergens: ['gluten'],
    tags: ['vegetarian', 'dairy-free', 'high-carb']
  },

  // ============ SNACKS ============
  {
    id: 'chips',
    name: 'Chips',
    category: 'snacks',
    portionG: 30,
    kcal: 536, protein: 7, fat: 35, carbs: 53,
    fiber: 4, sugar: 0.4, sodium: 530,
    calcium: 24, iron: 1.6, potassium: 1275, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'popcorn',
    name: 'Popcorn',
    category: 'snacks',
    portionG: 25,
    kcal: 387, protein: 12, fat: 4.5, carbs: 78,
    fiber: 15, sugar: 0.9, sodium: 8,
    calcium: 7, iron: 3.2, potassium: 329, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'protein-bar',
    name: 'Barre protéinée',
    category: 'snacks',
    portionG: 60,
    kcal: 380, protein: 33, fat: 12, carbs: 35,
    fiber: 5, sugar: 10, sodium: 240,
    calcium: 250, iron: 4.5, potassium: 280, vitaminD: 80,
    allergens: ['lait', 'soja', 'fruits-à-coque'],
    tags: ['vegetarian', 'high-protein']
  },
  {
    id: 'trail-mix',
    name: 'Trail mix',
    category: 'snacks',
    portionG: 50,
    kcal: 462, protein: 14, fat: 29, carbs: 45,
    fiber: 5, sugar: 28, sodium: 230,
    calcium: 80, iron: 2.8, potassium: 590, vitaminD: 0,
    allergens: ['fruits-à-coque', 'arachide', 'soja'],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'pretzels',
    name: 'Pretzels',
    category: 'snacks',
    portionG: 30,
    kcal: 380, protein: 10, fat: 3, carbs: 80,
    fiber: 3, sugar: 2, sodium: 1240,
    calcium: 22, iron: 4.6, potassium: 220, vitaminD: 0,
    allergens: ['gluten'],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'dairy-free', 'high-carb']
  },
  {
    id: 'crackers',
    name: 'Crackers',
    category: 'snacks',
    portionG: 30,
    kcal: 502, protein: 9, fat: 25, carbs: 60,
    fiber: 3, sugar: 5, sodium: 925,
    calcium: 110, iron: 4.5, potassium: 130, vitaminD: 0,
    allergens: ['gluten'],
    tags: ['vegetarian', 'high-carb']
  },
  {
    id: 'banana',
    name: 'Banane',
    category: 'snacks',
    portionG: 120,
    kcal: 89, protein: 1.1, fat: 0.3, carbs: 23,
    fiber: 2.6, sugar: 12, sodium: 1,
    calcium: 5, iron: 0.3, potassium: 358, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'apple',
    name: 'Pomme',
    category: 'snacks',
    portionG: 180,
    kcal: 52, protein: 0.3, fat: 0.2, carbs: 14,
    fiber: 2.4, sugar: 10, sodium: 1,
    calcium: 6, iron: 0.1, potassium: 107, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'candy',
    name: 'Bonbons',
    category: 'snacks',
    portionG: 40,
    kcal: 396, protein: 0, fat: 0.1, carbs: 98,
    fiber: 0, sugar: 70, sodium: 33,
    calcium: 4, iron: 0.4, potassium: 5, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'gluten-free', 'dairy-free', 'high-carb']
  },
  {
    id: 'beef-jerky',
    name: 'Beef jerky',
    category: 'snacks',
    portionG: 30,
    kcal: 410, protein: 33, fat: 26, carbs: 11,
    fiber: 1, sugar: 9, sodium: 1785,
    calcium: 20, iron: 5.4, potassium: 597, vitaminD: 2,
    allergens: ['soja'],
    tags: ['gluten-free', 'dairy-free', 'high-protein', 'low-carb']
  },
  {
    id: 'almonds',
    name: 'Amandes',
    category: 'snacks',
    portionG: 30,
    kcal: 579, protein: 21, fat: 50, carbs: 22,
    fiber: 12, sugar: 4, sodium: 1,
    calcium: 269, iron: 3.7, potassium: 733, vitaminD: 0,
    allergens: ['fruits-à-coque'],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'peanut-butter',
    name: 'Beurre de cacahuète',
    category: 'snacks',
    portionG: 32,
    kcal: 588, protein: 25, fat: 50, carbs: 20,
    fiber: 6, sugar: 9, sodium: 480,
    calcium: 49, iron: 1.9, potassium: 649, vitaminD: 0,
    allergens: ['arachide'],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free', 'high-protein']
  },

  // ============ BOISSONS ============
  {
    id: 'coffee-black',
    name: 'Café noir',
    category: 'drinks',
    portionG: 240,
    kcal: 2, protein: 0.1, fat: 0, carbs: 0,
    fiber: 0, sugar: 0, sodium: 5,
    calcium: 2, iron: 0, potassium: 49, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free', 'low-carb'],
    notes: 'Quasi nul'
  },
  {
    id: 'espresso',
    name: 'Espresso',
    category: 'drinks',
    portionG: 30,
    kcal: 9, protein: 0.1, fat: 0.2, carbs: 1.7,
    fiber: 0, sugar: 0, sodium: 14,
    calcium: 2, iron: 0.1, potassium: 115, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'latte',
    name: 'Latte',
    category: 'drinks',
    portionG: 350,
    kcal: 56, protein: 3, fat: 3, carbs: 5,
    fiber: 0, sugar: 5, sodium: 35,
    calcium: 100, iron: 0, potassium: 130, vitaminD: 25,
    allergens: ['lait'],
    tags: ['vegetarian', 'halal', 'kosher', 'gluten-free']
  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    category: 'drinks',
    portionG: 180,
    kcal: 39, protein: 2, fat: 2, carbs: 3,
    fiber: 0, sugar: 3, sodium: 22,
    calcium: 75, iron: 0, potassium: 95, vitaminD: 18,
    allergens: ['lait'],
    tags: ['vegetarian', 'halal', 'kosher', 'gluten-free']
  },
  {
    id: 'tea',
    name: 'Thé',
    category: 'drinks',
    portionG: 240,
    kcal: 1, protein: 0, fat: 0, carbs: 0.3,
    fiber: 0, sugar: 0, sodium: 3,
    calcium: 0, iron: 0, potassium: 37, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'hot-chocolate',
    name: 'Chocolat chaud',
    category: 'drinks',
    portionG: 250,
    kcal: 77, protein: 3.5, fat: 2.5, carbs: 11,
    fiber: 1, sugar: 9, sodium: 45,
    calcium: 110, iron: 0.4, potassium: 200, vitaminD: 20,
    allergens: ['lait'],
    tags: ['vegetarian', 'halal']
  },
  {
    id: 'soda',
    name: 'Soda (cola)',
    category: 'drinks',
    portionG: 355,
    kcal: 42, protein: 0, fat: 0, carbs: 11,
    fiber: 0, sugar: 11, sodium: 4,
    calcium: 2, iron: 0, potassium: 2, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'lemonade',
    name: 'Lemonade',
    category: 'drinks',
    portionG: 350,
    kcal: 40, protein: 0.1, fat: 0, carbs: 10,
    fiber: 0.1, sugar: 9, sodium: 4,
    calcium: 4, iron: 0.1, potassium: 22, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'orange-juice',
    name: "Jus d'orange",
    category: 'drinks',
    portionG: 250,
    kcal: 45, protein: 0.7, fat: 0.2, carbs: 10,
    fiber: 0.2, sugar: 8, sodium: 1,
    calcium: 11, iron: 0.2, potassium: 200, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
  {
    id: 'milkshake',
    name: 'Milkshake',
    category: 'drinks',
    portionG: 350,
    kcal: 112, protein: 3.5, fat: 3, carbs: 18,
    fiber: 0.3, sugar: 17, sodium: 95,
    calcium: 120, iron: 0.1, potassium: 180, vitaminD: 12,
    allergens: ['lait'],
    tags: ['vegetarian', 'halal'],
    notes: 'Densité calorique'
  },
  {
    id: 'energy-drink',
    name: 'Boisson énergétique',
    category: 'drinks',
    portionG: 250,
    kcal: 45, protein: 0.4, fat: 0, carbs: 11,
    fiber: 0, sugar: 11, sodium: 80,
    calcium: 4, iron: 0, potassium: 8, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'gluten-free', 'dairy-free']
  },
  {
    id: 'chocolate-milk',
    name: 'Lait chocolaté',
    category: 'drinks',
    portionG: 250,
    kcal: 83, protein: 3.2, fat: 2, carbs: 13,
    fiber: 0.6, sugar: 12, sodium: 60,
    calcium: 112, iron: 0.2, potassium: 168, vitaminD: 40,
    allergens: ['lait'],
    tags: ['vegetarian', 'halal']
  },
  {
    id: 'protein-shake',
    name: 'Protein shake (whey)',
    category: 'drinks',
    portionG: 300,
    kcal: 100, protein: 20, fat: 1.5, carbs: 4,
    fiber: 0.5, sugar: 2, sodium: 90,
    calcium: 150, iron: 0.5, potassium: 220, vitaminD: 40,
    allergens: ['lait', 'soja'],
    tags: ['vegetarian', 'halal', 'gluten-free', 'high-protein', 'low-carb']
  },
  {
    id: 'water',
    name: 'Eau',
    category: 'drinks',
    portionG: 500,
    kcal: 0, protein: 0, fat: 0, carbs: 0,
    fiber: 0, sugar: 0, sodium: 2,
    calcium: 4, iron: 0, potassium: 0, vitaminD: 0,
    allergens: [],
    tags: ['vegetarian', 'vegan', 'halal', 'kosher', 'gluten-free', 'dairy-free']
  },
];

Object.freeze(window.FOODS_DB);
