/* =============================================================
 * muscumoov — Nutrition module — Meals database
 *
 * Self-contained JS module loaded via <script>.
 * Exposes:
 *   - window.MEAL_OBJECTIVES  (array of { id, label })
 *   - window.MEALS_DB         (array of meal combos with cookable recipes)
 *
 * Quantities listed in `ingredients[].baseG` are calibrated for the
 * reference profile (80 kg, 180 cm). The runtime engine scales them
 * using the formula in NUTRITION-SPEC.md §7 :
 *   qty_user = qty_base * (poids_user / 80) * (1 + (taille_user - 180)/180 * 0.3)
 * ============================================================= */

window.MEAL_OBJECTIVES = [
  { id: 'performance',   label: 'Performance' },
  { id: 'endurance',     label: 'Endurance' },
  { id: 'mass-gain',     label: 'Prise de masse' },
  { id: 'cutting',       label: 'Sèche' },
  { id: 'maintenance',   label: 'Maintien' },
  { id: 'recovery',      label: 'Récupération' },
  { id: 'pre-match',     label: 'Pré-match' },
  { id: 'match-day',     label: 'Jour de match' },
  { id: 'post-training', label: 'Post-training' },
  { id: 'vegan',         label: 'Vegan' },
  { id: 'light',         label: 'Léger' },
  { id: 'high-protein',  label: 'Hautes protéines' },
];

window.MEALS_DB = [
  /* =========================================================
   * PETITS-DÉJEUNERS (15)
   * ========================================================= */
  {
    id: 'breakfast-performance',
    name: 'Œufs brouillés, bagel & yaourt',
    type: 'breakfast',
    objectives: ['performance'],
    sports: ['soccer', 'basketball', 'football'],
    totals: { kcal: 780, protein: 45, carbs: 82, fat: 28 },
    ingredients: [
      { foodId: 'eggs-scrambled', name: 'Œufs brouillés', baseG: 150 },
      { foodId: 'bagel-plain',    name: 'Bagel nature',   baseG: 95 },
      { foodId: 'greek-yogurt',   name: 'Yaourt grec',    baseG: 185 },
      { foodId: 'banana',         name: 'Banane',         baseG: 110 },
      { foodId: 'granola',        name: 'Granola',        baseG: 20 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 8,
      servings: 1,
      steps: [
        'Casse les œufs dans un bol et bats-les rapidement à la fourchette avec une pincée de sel.',
        'Chauffe une poêle anti-adhésive à feu moyen-doux avec une noisette de beurre.',
        'Verse les œufs et remue doucement à la spatule jusqu\'à obtenir une texture crémeuse (5-6 min).',
        'Pendant ce temps, coupe le bagel en deux et fais-le griller au toaster.',
        'Sers les œufs sur le bagel toasté.',
        'À côté, dépose le yaourt grec saupoudré de granola et la banane tranchée.',
      ],
      tips: 'Pour booster les protéines, ajoute une demi-mesure de whey dans le yaourt.',
    },
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&h=400&fit=crop',
  },
  {
    id: 'campus-soccer-fuel',
    name: 'Porridge granola & smoothie',
    type: 'breakfast',
    objectives: ['endurance'],
    sports: ['soccer', 'track'],
    totals: { kcal: 850, protein: 38, carbs: 110, fat: 26 },
    ingredients: [
      { foodId: 'oatmeal',      name: 'Oatmeal (flocons cuits)', baseG: 220 },
      { foodId: 'granola',      name: 'Granola',                 baseG: 30 },
      { foodId: 'mixed-fruits', name: 'Fruits frais mélangés',   baseG: 150 },
      { foodId: 'smoothie',     name: 'Smoothie fruits',         baseG: 250 },
      { foodId: 'eggs-boiled',  name: 'Œufs durs',               baseG: 100 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 12,
      servings: 1,
      steps: [
        'Plonge les œufs dans une casserole d\'eau froide, porte à ébullition puis laisse cuire 9 min.',
        'Pendant ce temps, verse les flocons d\'avoine dans une casserole avec 2 fois leur volume de lait ou d\'eau.',
        'Laisse mijoter à feu doux 5 min en remuant, jusqu\'à obtenir une texture onctueuse.',
        'Transvase l\'oatmeal dans un bol, parsème de granola et de fruits frais.',
        'Égoutte et écale les œufs durs, dépose-les à côté.',
        'Mixe les fruits restants avec un peu de lait pour le smoothie et sers le tout ensemble.',
      ],
      tips: 'Prépare l\'oatmeal en overnight oats la veille pour gagner 10 min le matin.',
    },
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&h=400&fit=crop',
  },
  {
    id: 'lean-athlete-morning',
    name: 'Omelette légumes & toast avocat',
    type: 'breakfast',
    objectives: ['maintenance', 'cutting'],
    sports: ['soccer', 'tennis', 'track'],
    totals: { kcal: 650, protein: 35, carbs: 50, fat: 30 },
    ingredients: [
      { foodId: 'eggs-whole',     name: 'Œufs entiers',  baseG: 150 },
      { foodId: 'mixed-veggies',  name: 'Légumes (poivron, oignon, épinards)', baseG: 100 },
      { foodId: 'bread-whole',    name: 'Pain complet',  baseG: 60 },
      { foodId: 'avocado',        name: 'Avocat',        baseG: 80 },
      { foodId: 'mixed-fruits',   name: 'Fruits frais',  baseG: 120 },
    ],
    recipe: {
      prepMinutes: 6,
      cookMinutes: 8,
      servings: 1,
      steps: [
        'Émince les légumes (poivron, oignon, épinards) en petits morceaux.',
        'Fais revenir les légumes 3 min à feu vif dans une poêle avec un filet d\'huile d\'olive.',
        'Bats les œufs dans un bol, assaisonne sel-poivre, verse sur les légumes.',
        'Laisse prendre 2 min puis replie l\'omelette en deux et cuis encore 1 min.',
        'Fais griller le pain et écrase l\'avocat dessus avec un filet de citron.',
        'Sers l\'omelette avec le toast avocat et les fruits frais à côté.',
      ],
      tips: 'Remplace 1 œuf entier par 2 blancs pour alléger en lipides.',
    },
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&h=400&fit=crop',
  },
  {
    id: 'mass-gain-breakfast',
    name: 'Pancakes, bacon & œufs',
    type: 'breakfast',
    objectives: ['mass-gain'],
    sports: ['football', 'basketball'],
    totals: { kcal: 1050, protein: 48, carbs: 115, fat: 42 },
    ingredients: [
      { foodId: 'pancakes',    name: 'Pancakes',         baseG: 200 },
      { foodId: 'bacon',       name: 'Bacon',            baseG: 50 },
      { foodId: 'eggs-whole',  name: 'Œufs',             baseG: 120 },
      { foodId: 'smoothie',    name: 'Smoothie protéiné',baseG: 300 },
      { foodId: 'maple-syrup', name: 'Sirop d\'érable',  baseG: 30 },
    ],
    recipe: {
      prepMinutes: 8,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Prépare une pâte à pancakes (farine, lait, œuf, levure) et laisse reposer 5 min.',
        'Fais cuire le bacon à la poêle à feu moyen jusqu\'à ce qu\'il soit doré et croustillant.',
        'Réserve le bacon sur du papier absorbant, garde un peu de gras dans la poêle.',
        'Verse des louches de pâte pour cuire les pancakes 2 min de chaque côté.',
        'Dans la même poêle nettoyée, fais cuire les œufs au plat à feu doux.',
        'Mixe banane + lait + whey + beurre de cacahuète pour le smoothie.',
        'Dresse l\'assiette : pancakes nappés de sirop d\'érable, bacon, œufs et smoothie à côté.',
      ],
      tips: 'Ajoute des flocons d\'avoine dans la pâte à pancakes pour plus de glucides complexes.',
    },
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&h=400&fit=crop',
  },
  {
    id: 'recovery-breakfast',
    name: 'Burrito petit-déj & yaourt',
    type: 'breakfast',
    objectives: ['recovery', 'post-training'],
    sports: ['soccer', 'basketball', 'football'],
    totals: { kcal: 900, protein: 52, carbs: 85, fat: 35 },
    ingredients: [
      { foodId: 'breakfast-burrito', name: 'Breakfast burrito', baseG: 280 },
      { foodId: 'greek-yogurt',      name: 'Yaourt grec',       baseG: 200 },
      { foodId: 'mixed-fruits',      name: 'Fruits frais',      baseG: 150 },
      { foodId: 'honey',             name: 'Miel',              baseG: 15 },
    ],
    recipe: {
      prepMinutes: 8,
      cookMinutes: 10,
      servings: 1,
      steps: [
        'Brouille les œufs à feu doux dans une poêle avec un peu de beurre.',
        'Fais réchauffer la tortilla 30 sec dans une autre poêle sèche.',
        'Dispose au centre les œufs brouillés, du fromage râpé, des haricots noirs et de la salsa.',
        'Replie les côtés puis roule fermement le burrito sur lui-même.',
        'Repasse le burrito 1 min sur chaque face dans la poêle pour le dorer.',
        'Sers avec un grand bol de yaourt grec nappé de miel et garni de fruits frais coupés.',
      ],
      tips: 'Idéal dans les 60 min après l\'entraînement pour optimiser la récupération.',
    },
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=600&h=400&fit=crop',
  },
  {
    id: 'fast-campus-combo',
    name: 'Sandwich petit-déj & hash browns',
    type: 'breakfast',
    objectives: ['performance'],
    sports: ['soccer', 'basketball'],
    totals: { kcal: 880, protein: 40, carbs: 92, fat: 38 },
    ingredients: [
      { foodId: 'breakfast-sandwich', name: 'Breakfast sandwich (œuf, fromage, bacon)', baseG: 220 },
      { foodId: 'hash-browns',        name: 'Hash browns',                              baseG: 120 },
      { foodId: 'smoothie',           name: 'Smoothie fruits',                          baseG: 300 },
    ],
    recipe: {
      prepMinutes: 4,
      cookMinutes: 10,
      servings: 1,
      steps: [
        'Fais cuire le bacon et l\'œuf à la poêle pendant que tu toastes le muffin anglais.',
        'Pose une tranche de cheddar sur l\'œuf chaud pour la faire fondre.',
        'Assemble le sandwich : muffin, œuf-fromage, bacon, refermer.',
        'Dans une seconde poêle bien huilée, fais dorer les hash browns 4 min de chaque côté.',
        'Mixe les fruits avec du lait ou jus d\'orange pour le smoothie.',
        'Sers immédiatement, parfait à emporter en sortant de la chambre.',
      ],
      tips: 'Les hash browns surgelés cuits à l\'air fryer fonctionnent très bien (12 min à 200 °C).',
    },
    image: 'https://images.unsplash.com/photo-1592151450334-c64aeac0b80a?w=600&h=400&fit=crop',
  },
  {
    id: 'protein-stack',
    name: 'Omelette, bagel & barre protéinée',
    type: 'breakfast',
    objectives: ['high-protein'],
    sports: ['football', 'basketball'],
    totals: { kcal: 930, protein: 65, carbs: 85, fat: 30 },
    ingredients: [
      { foodId: 'eggs-whole',    name: 'Œufs',              baseG: 200 },
      { foodId: 'bagel-plain',   name: 'Bagel',             baseG: 100 },
      { foodId: 'protein-bar',   name: 'Barre protéinée',   baseG: 60 },
      { foodId: 'mixed-fruits',  name: 'Fruits frais',      baseG: 150 },
      { foodId: 'cheese-shred',  name: 'Fromage râpé',      baseG: 30 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 8,
      servings: 1,
      steps: [
        'Bats les œufs avec une pincée de sel et le fromage râpé.',
        'Chauffe une poêle anti-adhésive à feu moyen avec un peu d\'huile.',
        'Verse les œufs, laisse prendre puis replie en omelette baveuse au centre (4 min).',
        'Coupe le bagel en deux, toaste-le bien doré.',
        'Garnis le bagel de l\'omelette tranchée pour en faire un sandwich.',
        'Sers avec la barre protéinée et les fruits frais coupés en cubes.',
      ],
      tips: 'Choisis une barre à 20 g+ de protéines pour atteindre les 65 g totaux.',
    },
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&h=400&fit=crop',
  },
  {
    id: 'basketball-morning',
    name: 'Pain perdu, saucisses & yaourt',
    type: 'breakfast',
    objectives: ['match-day', 'performance'],
    sports: ['basketball'],
    totals: { kcal: 950, protein: 42, carbs: 105, fat: 38 },
    ingredients: [
      { foodId: 'french-toast', name: 'French toast',  baseG: 180 },
      { foodId: 'sausages',     name: 'Saucisses',     baseG: 80 },
      { foodId: 'greek-yogurt', name: 'Yaourt grec',   baseG: 150 },
      { foodId: 'mixed-fruits', name: 'Fruits frais',  baseG: 150 },
      { foodId: 'maple-syrup',  name: 'Sirop d\'érable',baseG: 25 },
    ],
    recipe: {
      prepMinutes: 7,
      cookMinutes: 12,
      servings: 1,
      steps: [
        'Fouette 2 œufs, du lait, une pincée de cannelle et un soupçon de sucre dans un plat creux.',
        'Trempe les tranches de pain dans le mélange jusqu\'à ce qu\'elles soient bien imbibées.',
        'Fais dorer le pain 2-3 min de chaque face dans une poêle beurrée à feu moyen.',
        'Dans une autre poêle, fais cuire les saucisses 6-8 min en les retournant régulièrement.',
        'Dresse les French toasts nappés de sirop d\'érable, saucisses à côté.',
        'Termine avec le yaourt grec garni de fruits frais coupés.',
      ],
      tips: 'À consommer 3 h avant le match pour une digestion optimale.',
    },
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&h=400&fit=crop',
  },
  {
    id: 'healthy-bowl-breakfast',
    name: 'Bowl yaourt, granola & porridge',
    type: 'breakfast',
    objectives: ['light', 'maintenance'],
    sports: ['tennis', 'track', 'soccer'],
    totals: { kcal: 620, protein: 28, carbs: 88, fat: 18 },
    ingredients: [
      { foodId: 'greek-yogurt',  name: 'Yaourt grec',        baseG: 200 },
      { foodId: 'granola',       name: 'Granola',            baseG: 40 },
      { foodId: 'mixed-fruits',  name: 'Fruits frais',       baseG: 180 },
      { foodId: 'oatmeal',       name: 'Oatmeal cuit',       baseG: 150 },
      { foodId: 'honey',         name: 'Miel',               baseG: 15 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 5,
      servings: 1,
      steps: [
        'Verse les flocons d\'avoine dans une casserole avec 1,5 fois leur volume d\'eau ou de lait.',
        'Laisse mijoter à feu doux 4 min en remuant régulièrement.',
        'Transvase l\'oatmeal dans un grand bol et laisse tiédir 1 min.',
        'Ajoute par-dessus le yaourt grec en couche généreuse.',
        'Parsème de granola, dispose les fruits frais coupés et nappe d\'un trait de miel.',
        'Déguste immédiatement pour profiter du contraste chaud-froid.',
      ],
      tips: 'Varie les fruits selon la saison : myrtilles, framboises, mangue, kiwi.',
    },
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&h=400&fit=crop',
  },
  {
    id: 'campus-bulk-meal',
    name: 'Burrito petit-déj & pancakes',
    type: 'breakfast',
    objectives: ['mass-gain'],
    sports: ['football'],
    totals: { kcal: 1200, protein: 55, carbs: 140, fat: 42 },
    ingredients: [
      { foodId: 'breakfast-burrito', name: 'Breakfast burrito', baseG: 300 },
      { foodId: 'pancakes',          name: 'Pancakes',          baseG: 220 },
      { foodId: 'smoothie',          name: 'Smoothie protéiné', baseG: 350 },
      { foodId: 'maple-syrup',       name: 'Sirop d\'érable',   baseG: 30 },
    ],
    recipe: {
      prepMinutes: 10,
      cookMinutes: 18,
      servings: 1,
      steps: [
        'Prépare la pâte à pancakes et laisse reposer pendant que tu commences le burrito.',
        'Brouille les œufs avec du fromage et fais cuire des haricots noirs à la poêle.',
        'Réchauffe une grande tortilla, garnis-la d\'œufs, haricots, salsa et roule fermement.',
        'Repasse le burrito 1 min de chaque côté pour le dorer.',
        'Pendant ce temps, cuis les pancakes par lots de 2-3 dans une poêle chaude.',
        'Mixe lait + banane + whey + beurre de cacahuète + flocons pour le smoothie.',
        'Sers le tout en assiette XL avec sirop d\'érable sur les pancakes.',
      ],
      tips: 'Conviens parfaitement pour les jours de double-séance ou de musculation lourde.',
    },
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&h=400&fit=crop',
  },
  {
    id: 'vegan-athlete-breakfast',
    name: 'Tofu grillé & porridge fruits',
    type: 'breakfast',
    objectives: ['vegan'],
    sports: ['soccer', 'track', 'tennis'],
    totals: { kcal: 710, protein: 32, carbs: 95, fat: 20 },
    ingredients: [
      { foodId: 'tofu',         name: 'Tofu ferme',         baseG: 180 },
      { foodId: 'oatmeal',      name: 'Oatmeal cuit',       baseG: 200 },
      { foodId: 'mixed-fruits', name: 'Fruits frais',       baseG: 150 },
      { foodId: 'smoothie-vegan', name: 'Smoothie végétal', baseG: 250 },
      { foodId: 'almond-butter',name: 'Beurre d\'amande',   baseG: 15 },
    ],
    recipe: {
      prepMinutes: 6,
      cookMinutes: 10,
      servings: 1,
      steps: [
        'Égoutte le tofu, presse-le entre deux torchons puis coupe-le en cubes.',
        'Fais revenir le tofu 6 min dans une poêle bien chaude avec un peu d\'huile et du paprika.',
        'En parallèle, cuis les flocons d\'avoine dans du lait d\'amande à feu doux 4 min.',
        'Verse l\'oatmeal dans un bol, ajoute une cuillère de beurre d\'amande.',
        'Dispose les fruits frais coupés par-dessus.',
        'Mixe banane, lait végétal et fruits rouges pour le smoothie.',
        'Sers le tofu doré à part avec un trait de sauce soja.',
      ],
      tips: 'Ajoute des graines de chia pour un boost d\'oméga-3 végétaux.',
    },
    image: 'https://images.unsplash.com/photo-1603046891744-1f76eb10aec1?w=600&h=400&fit=crop',
  },
  {
    id: 'high-carb-match-day',
    name: 'Bagel, pancakes & fruits',
    type: 'breakfast',
    objectives: ['match-day'],
    sports: ['soccer', 'basketball', 'tennis'],
    totals: { kcal: 980, protein: 35, carbs: 145, fat: 25 },
    ingredients: [
      { foodId: 'bagel-plain',   name: 'Bagel',          baseG: 110 },
      { foodId: 'pancakes',      name: 'Pancakes',       baseG: 180 },
      { foodId: 'mixed-fruits',  name: 'Fruits frais',   baseG: 200 },
      { foodId: 'orange-juice',  name: 'Jus d\'orange',  baseG: 250 },
      { foodId: 'eggs-whole',    name: 'Œufs',           baseG: 100 },
      { foodId: 'honey',         name: 'Miel',           baseG: 20 },
    ],
    recipe: {
      prepMinutes: 6,
      cookMinutes: 12,
      servings: 1,
      steps: [
        'Cuis les pancakes à la poêle, 2 min par face à feu moyen.',
        'Toaste le bagel coupé en deux jusqu\'à ce qu\'il soit doré.',
        'Cuis les œufs au plat dans une poêle légèrement huilée à feu doux.',
        'Tartine le bagel d\'un peu de miel.',
        'Dresse l\'assiette : pancakes nappés de miel, œufs au plat, bagel à côté.',
        'Ajoute les fruits frais coupés et sers avec le grand verre de jus d\'orange.',
      ],
      tips: 'À consommer 3 à 4 h avant le coup d\'envoi pour stocker un max de glycogène.',
    },
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&h=400&fit=crop',
  },
  {
    id: 'cutting-breakfast',
    name: 'Omelette blancs d\'œufs & yaourt',
    type: 'breakfast',
    objectives: ['cutting', 'high-protein'],
    sports: ['basketball', 'football', 'tennis'],
    totals: { kcal: 520, protein: 50, carbs: 35, fat: 15 },
    ingredients: [
      { foodId: 'egg-whites',   name: 'Blancs d\'œufs',  baseG: 250 },
      { foodId: 'mixed-veggies',name: 'Légumes (épinards, champignons)', baseG: 100 },
      { foodId: 'greek-yogurt', name: 'Yaourt grec 0%',  baseG: 200 },
      { foodId: 'mixed-fruits', name: 'Fruits rouges',   baseG: 120 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 6,
      servings: 1,
      steps: [
        'Émince les champignons et lave les épinards.',
        'Fais revenir les légumes 2 min dans une poêle anti-adhésive avec un filet d\'huile.',
        'Verse les blancs d\'œufs battus, assaisonne sel-poivre.',
        'Laisse prendre 3 min puis replie l\'omelette en deux.',
        'Sers dans une assiette avec le yaourt grec 0 % à côté.',
        'Termine avec les fruits rouges déposés sur le yaourt.',
      ],
      tips: 'Utilise des blancs d\'œufs en bouteille pour gagner du temps et éviter le gaspillage.',
    },
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&h=400&fit=crop',
  },
  {
    id: 'classic-american-campus',
    name: 'Donut, bacon & œufs',
    type: 'breakfast',
    objectives: ['maintenance'],
    sports: ['football', 'baseball'],
    totals: { kcal: 760, protein: 28, carbs: 65, fat: 40 },
    ingredients: [
      { foodId: 'donut',      name: 'Donut',  baseG: 80 },
      { foodId: 'bacon',      name: 'Bacon',  baseG: 60 },
      { foodId: 'eggs-whole', name: 'Œufs',   baseG: 120 },
      { foodId: 'coffee',     name: 'Café',   baseG: 240 },
    ],
    recipe: {
      prepMinutes: 3,
      cookMinutes: 10,
      servings: 1,
      steps: [
        'Lance la cafetière ou prépare ton expresso préféré.',
        'Pose les tranches de bacon dans une poêle froide, allume à feu moyen.',
        'Laisse cuire le bacon 6-8 min en le retournant à mi-cuisson, jusqu\'à ce qu\'il soit croustillant.',
        'Réserve le bacon sur du papier absorbant, garde un peu de gras dans la poêle.',
        'Casse les œufs dans la poêle, cuis-les au plat 3 min à feu doux.',
        'Sers les œufs et le bacon avec le donut à côté et le café fumant.',
      ],
      tips: 'Combo occasionnel : à garder pour 1-2 fois par semaine maximum.',
    },
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&h=400&fit=crop',
  },
  {
    id: 'heavy-training-breakfast',
    name: 'Gaufres, saucisses & yaourt',
    type: 'breakfast',
    objectives: ['performance', 'mass-gain'],
    sports: ['football', 'basketball'],
    totals: { kcal: 1100, protein: 50, carbs: 125, fat: 42 },
    ingredients: [
      { foodId: 'waffles',      name: 'Gaufres',          baseG: 200 },
      { foodId: 'sausages',     name: 'Saucisses',        baseG: 100 },
      { foodId: 'smoothie',     name: 'Smoothie protéiné',baseG: 300 },
      { foodId: 'greek-yogurt', name: 'Yaourt grec',      baseG: 180 },
      { foodId: 'maple-syrup',  name: 'Sirop d\'érable',  baseG: 30 },
    ],
    recipe: {
      prepMinutes: 8,
      cookMinutes: 12,
      servings: 1,
      steps: [
        'Préchauffe le gaufrier ou sors les gaufres surgelées du congélateur.',
        'Cuis les gaufres jusqu\'à ce qu\'elles soient bien dorées et croustillantes.',
        'Pendant ce temps, fais cuire les saucisses à la poêle, 8 min en les retournant.',
        'Mixe lait + banane + whey + flocons d\'avoine + beurre de cacahuète pour le smoothie.',
        'Dresse les gaufres dans une assiette, nappées de sirop d\'érable.',
        'Ajoute les saucisses et le bol de yaourt grec à côté.',
        'Bois le smoothie en accompagnement.',
      ],
      tips: 'Parfait avant une grosse séance de muscu ou un entraînement double.',
    },
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&h=400&fit=crop',
  },

  /* =========================================================
   * DÉJEUNERS (15)
   * ========================================================= */
  {
    id: 'chicken-bowl',
    name: 'Bowl poulet, riz & avocat',
    type: 'lunch',
    objectives: ['maintenance', 'performance'],
    sports: ['soccer', 'basketball', 'tennis'],
    totals: { kcal: 780, protein: 52, carbs: 75, fat: 24 },
    ingredients: [
      { foodId: 'chicken-breast', name: 'Poulet grillé', baseG: 180 },
      { foodId: 'rice-white',     name: 'Riz blanc cuit',baseG: 250 },
      { foodId: 'avocado',        name: 'Avocat',        baseG: 70 },
      { foodId: 'mixed-veggies',  name: 'Légumes (brocoli, poivron)', baseG: 150 },
    ],
    recipe: {
      prepMinutes: 8,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Lance la cuisson du riz dans une casserole d\'eau salée (15 min).',
        'Coupe le poulet en escalopes fines, assaisonne sel, poivre, paprika.',
        'Fais griller le poulet 4 min de chaque côté dans une poêle bien chaude.',
        'En parallèle, fais sauter les légumes 5 min à la poêle avec un filet d\'huile et de l\'ail.',
        'Égoutte le riz et dépose-le dans un bol.',
        'Tranche le poulet et l\'avocat, dispose-les sur le riz avec les légumes.',
        'Termine par un filet d\'huile d\'olive et un jus de citron.',
      ],
      tips: 'Double les portions et garde une part pour le déjeuner du lendemain.',
    },
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop',
  },
  {
    id: 'power-burrito',
    name: 'Burrito poulet, riz & haricots',
    type: 'lunch',
    objectives: ['performance', 'mass-gain'],
    sports: ['football', 'basketball'],
    totals: { kcal: 920, protein: 48, carbs: 90, fat: 32 },
    ingredients: [
      { foodId: 'tortilla',       name: 'Tortilla',     baseG: 80 },
      { foodId: 'chicken-breast', name: 'Poulet',       baseG: 150 },
      { foodId: 'rice-white',     name: 'Riz cuit',     baseG: 180 },
      { foodId: 'black-beans',    name: 'Haricots noirs',baseG: 120 },
      { foodId: 'guacamole',      name: 'Guacamole',    baseG: 60 },
      { foodId: 'cheese-shred',   name: 'Fromage râpé', baseG: 30 },
    ],
    recipe: {
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Cuis le riz dans une casserole d\'eau salée 12-15 min puis égoutte-le.',
        'Découpe le poulet en lanières, assaisonne avec cumin, paprika et un peu d\'ail.',
        'Fais sauter le poulet 6 min dans une poêle chaude jusqu\'à ce qu\'il soit doré.',
        'Réchauffe les haricots noirs à feu doux avec une pincée de sel.',
        'Pose la tortilla à plat, dispose riz, poulet, haricots, fromage et guacamole au centre.',
        'Replie les côtés puis roule fermement en serrant bien.',
        'Repasse 1 min de chaque côté à la poêle sèche pour dorer le burrito.',
      ],
      tips: 'Pour la version "wet", nappe de sauce enchilada avant de servir.',
    },
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&h=400&fit=crop',
  },
  {
    id: 'pasta-beef',
    name: 'Pâtes au bœuf, sauce tomate',
    type: 'lunch',
    objectives: ['mass-gain', 'high-protein'],
    sports: ['football', 'basketball'],
    totals: { kcal: 890, protein: 55, carbs: 95, fat: 22 },
    ingredients: [
      { foodId: 'pasta',         name: 'Pâtes',        baseG: 250 },
      { foodId: 'beef-lean',     name: 'Steak haché maigre 5%', baseG: 180 },
      { foodId: 'tomato-sauce',  name: 'Sauce tomate', baseG: 150 },
      { foodId: 'parmesan',      name: 'Parmesan',     baseG: 20 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Porte une grande casserole d\'eau salée à ébullition et plonge les pâtes.',
        'Pendant ce temps, fais revenir le steak haché dans une poêle chaude à feu vif.',
        'Émiette la viande à la spatule et laisse cuire 5 min jusqu\'à coloration.',
        'Ajoute la sauce tomate, une pincée d\'origan, sel et poivre.',
        'Laisse mijoter 6-8 min à feu doux pendant que les pâtes cuisent al dente.',
        'Égoutte les pâtes en gardant une louche d\'eau de cuisson.',
        'Mélange pâtes et sauce, ajuste avec l\'eau de cuisson, parsème de parmesan.',
      ],
      tips: 'Ajoute une cuillère de mascarpone pour une sauce plus onctueuse.',
    },
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&h=400&fit=crop',
  },
  {
    id: 'turkey-rice',
    name: 'Dinde, riz basmati & légumes',
    type: 'lunch',
    objectives: ['cutting', 'maintenance', 'high-protein'],
    sports: ['tennis', 'soccer', 'track'],
    totals: { kcal: 720, protein: 50, carbs: 72, fat: 14 },
    ingredients: [
      { foodId: 'turkey-breast',  name: 'Blanc de dinde', baseG: 180 },
      { foodId: 'rice-basmati',   name: 'Riz basmati cuit', baseG: 230 },
      { foodId: 'mixed-veggies',  name: 'Légumes (courgette, carotte)', baseG: 180 },
    ],
    recipe: {
      prepMinutes: 6,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Lance la cuisson du riz basmati (12 min dans 1,5 fois son volume d\'eau salée).',
        'Coupe le blanc de dinde en escalopes fines, assaisonne sel, poivre, herbes.',
        'Fais cuire la dinde 4 min de chaque côté dans une poêle anti-adhésive avec un filet d\'huile.',
        'Découpe les légumes en bâtonnets, fais-les sauter 6 min avec ail et un peu de sauce soja.',
        'Égrène le riz à la fourchette dans une assiette.',
        'Tranche la dinde et dépose-la avec les légumes sur le riz.',
      ],
      tips: 'Idéal en sèche : peu de lipides, beaucoup de protéines maigres.',
    },
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop',
  },
  {
    id: 'campus-burger',
    name: 'Cheeseburger & potatoes',
    type: 'lunch',
    objectives: ['mass-gain'],
    sports: ['football'],
    totals: { kcal: 980, protein: 42, carbs: 88, fat: 40 },
    ingredients: [
      { foodId: 'cheeseburger', name: 'Cheeseburger', baseG: 280 },
      { foodId: 'fries',        name: 'Potatoes',     baseG: 180 },
      { foodId: 'mixed-fruits', name: 'Fruit',        baseG: 150 },
    ],
    recipe: {
      prepMinutes: 8,
      cookMinutes: 12,
      servings: 1,
      steps: [
        'Préchauffe le four à 220 °C pour les potatoes.',
        'Coupe les pommes de terre en quartiers, mélange avec huile, paprika, sel.',
        'Enfourne 20 min en remuant à mi-cuisson.',
        'Forme un steak haché de 150 g, assaisonne sel-poivre généreusement.',
        'Fais cuire le steak 3 min par face dans une poêle bien chaude, ajoute une tranche de cheddar.',
        'Toaste les pains à burger et garnis : sauce, salade, tomate, oignon, steak-cheddar.',
        'Sers avec les potatoes et le fruit en dessert.',
      ],
      tips: 'Choisis du bœuf 15 % MG pour un steak juteux mais pas trop gras.',
    },
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=400&fit=crop',
  },
  {
    id: 'salmon-rice',
    name: 'Saumon, riz & avocat',
    type: 'lunch',
    objectives: ['recovery', 'performance'],
    sports: ['soccer', 'swimming', 'tennis'],
    totals: { kcal: 840, protein: 44, carbs: 70, fat: 35 },
    ingredients: [
      { foodId: 'salmon',     name: 'Saumon',       baseG: 180 },
      { foodId: 'rice-white', name: 'Riz cuit',     baseG: 230 },
      { foodId: 'avocado',    name: 'Avocat',       baseG: 90 },
      { foodId: 'soy-sauce',  name: 'Sauce soja',   baseG: 15 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Lance la cuisson du riz (12 min dans de l\'eau salée).',
        'Assaisonne le pavé de saumon avec sel, poivre et un trait de sauce soja.',
        'Chauffe une poêle à feu moyen-vif avec une cuillère d\'huile.',
        'Pose le saumon côté peau, cuis 4 min sans bouger, puis retourne et cuis 2-3 min.',
        'Émince l\'avocat en lamelles.',
        'Dresse le riz dans un bol, dépose le saumon et l\'avocat par-dessus.',
        'Termine avec un filet de sauce soja et quelques graines de sésame.',
      ],
      tips: 'Oméga-3 anti-inflammatoires : parfait après un gros match.',
    },
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
  },
  {
    id: 'athlete-pasta',
    name: 'Pâtes à la viande & parmesan',
    type: 'lunch',
    objectives: ['performance', 'endurance'],
    sports: ['soccer', 'track'],
    totals: { kcal: 920, protein: 52, carbs: 100, fat: 24 },
    ingredients: [
      { foodId: 'pasta',         name: 'Pâtes',           baseG: 250 },
      { foodId: 'beef-lean',     name: 'Viande maigre hachée', baseG: 160 },
      { foodId: 'parmesan',      name: 'Parmesan',        baseG: 30 },
      { foodId: 'tomato-sauce',  name: 'Sauce tomate',    baseG: 120 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Porte une grande casserole d\'eau salée à ébullition pour les pâtes.',
        'Fais revenir la viande hachée dans une poêle chaude, émiette à la spatule.',
        'Quand la viande est dorée, ajoute la sauce tomate, sel, poivre, basilic.',
        'Laisse mijoter à feu doux 7 min.',
        'Cuis les pâtes al dente selon les indications du paquet.',
        'Égoutte les pâtes, mélange-les avec la sauce dans la poêle.',
        'Sers généreusement parsemé de parmesan râpé.',
      ],
      tips: 'À privilégier la veille d\'un match pour faire le plein de glycogène.',
    },
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&h=400&fit=crop',
  },
  {
    id: 'teriyaki-bowl',
    name: 'Bowl poulet teriyaki',
    type: 'lunch',
    objectives: ['performance'],
    sports: ['basketball', 'soccer'],
    totals: { kcal: 790, protein: 46, carbs: 88, fat: 18 },
    ingredients: [
      { foodId: 'chicken-breast', name: 'Poulet', baseG: 170 },
      { foodId: 'rice-white',     name: 'Riz cuit', baseG: 240 },
      { foodId: 'mixed-veggies',  name: 'Légumes (brocoli, carotte)', baseG: 150 },
      { foodId: 'teriyaki-sauce', name: 'Sauce teriyaki', baseG: 30 },
    ],
    recipe: {
      prepMinutes: 8,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Lance la cuisson du riz.',
        'Coupe le poulet en cubes, fais-le sauter à feu vif dans une poêle huilée 5 min.',
        'Verse la sauce teriyaki sur le poulet, baisse à feu moyen.',
        'Laisse réduire la sauce 3 min en remuant pour bien enrober les cubes.',
        'Dans une autre poêle ou wok, fais sauter les légumes 5 min avec un peu d\'ail.',
        'Dresse le riz dans un bol, ajoute le poulet teriyaki et les légumes.',
        'Parsème de graines de sésame et d\'oignons verts émincés.',
      ],
      tips: 'À consommer 2 h avant l\'entraînement pour avoir l\'énergie nécessaire.',
    },
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
  },
  {
    id: 'poke-power',
    name: 'Poke saumon, mangue & avocat',
    type: 'lunch',
    objectives: ['performance', 'recovery'],
    sports: ['soccer', 'swimming'],
    totals: { kcal: 810, protein: 42, carbs: 78, fat: 28 },
    ingredients: [
      { foodId: 'rice-white',  name: 'Riz cuit',       baseG: 220 },
      { foodId: 'salmon-raw',  name: 'Saumon cru',     baseG: 150 },
      { foodId: 'mango',       name: 'Mangue',         baseG: 100 },
      { foodId: 'avocado',     name: 'Avocat',         baseG: 80 },
      { foodId: 'soy-sauce',   name: 'Sauce soja',     baseG: 15 },
    ],
    recipe: {
      prepMinutes: 12,
      cookMinutes: 12,
      servings: 1,
      steps: [
        'Cuis le riz selon le paquet puis laisse tiédir avec un trait de vinaigre de riz.',
        'Coupe le saumon cru en cubes réguliers de 1,5 cm.',
        'Mélange le saumon avec sauce soja, sésame, un peu d\'huile de sésame, oignons verts.',
        'Laisse mariner 5 min au frais.',
        'Découpe la mangue et l\'avocat en cubes.',
        'Dispose le riz tiède dans un bol, dépose harmonieusement saumon, mangue, avocat.',
        'Termine avec graines de sésame, algues ou edamame selon tes envies.',
      ],
      tips: 'Utilise du saumon "sashimi grade" pour la sécurité alimentaire.',
    },
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
  },
  {
    id: 'mexican-fuel',
    name: 'Bowl viande, riz & haricots',
    type: 'lunch',
    objectives: ['match-day', 'performance'],
    sports: ['soccer', 'football'],
    totals: { kcal: 930, protein: 50, carbs: 102, fat: 25 },
    ingredients: [
      { foodId: 'rice-white',     name: 'Riz cuit',      baseG: 220 },
      { foodId: 'beef-lean',      name: 'Viande hachée', baseG: 160 },
      { foodId: 'black-beans',    name: 'Haricots noirs',baseG: 150 },
      { foodId: 'guacamole',      name: 'Guacamole',     baseG: 70 },
      { foodId: 'salsa',          name: 'Salsa',         baseG: 60 },
    ],
    recipe: {
      prepMinutes: 8,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Cuis le riz dans de l\'eau salée 12 min.',
        'Fais revenir la viande hachée à feu vif avec cumin, paprika, ail et oignon.',
        'Émiette à la spatule, laisse colorer 6 min jusqu\'à ce qu\'elle soit bien dorée.',
        'Réchauffe les haricots noirs à feu doux dans une petite casserole.',
        'Dresse le riz dans un grand bol, ajoute la viande, les haricots.',
        'Couronne de guacamole, salsa, coriandre fraîche et un filet de citron vert.',
      ],
      tips: 'Ajoute des chips de tortilla émiettées pour le croquant.',
    },
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&h=400&fit=crop',
  },
  {
    id: 'lean-chicken',
    name: 'Poulet grillé & patate douce',
    type: 'lunch',
    objectives: ['cutting', 'high-protein'],
    sports: ['tennis', 'basketball', 'track'],
    totals: { kcal: 650, protein: 56, carbs: 48, fat: 16 },
    ingredients: [
      { foodId: 'chicken-breast', name: 'Poulet grillé',  baseG: 200 },
      { foodId: 'sweet-potato',   name: 'Patate douce',   baseG: 200 },
      { foodId: 'salad-greens',   name: 'Salade verte mélangée', baseG: 120 },
      { foodId: 'olive-oil',      name: 'Huile d\'olive', baseG: 10 },
    ],
    recipe: {
      prepMinutes: 6,
      cookMinutes: 25,
      servings: 1,
      steps: [
        'Préchauffe le four à 200 °C.',
        'Lave et coupe la patate douce en cubes, enrobe d\'un peu d\'huile et de paprika.',
        'Enfourne 20-25 min jusqu\'à ce que les cubes soient tendres et caramélisés.',
        'Assaisonne le poulet sel, poivre, herbes de Provence.',
        'Fais-le griller 4 min par face dans une poêle ou au grill.',
        'Prépare la salade dans un saladier avec un filet d\'huile d\'olive et de vinaigre.',
        'Tranche le poulet, dresse l\'assiette avec patate douce et salade.',
      ],
      tips: 'Top en sèche : 56 g de protéines pour seulement 650 kcal.',
    },
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
  },
  {
    id: 'sushi-lunch',
    name: 'Sushi & California rolls',
    type: 'lunch',
    objectives: ['light', 'maintenance'],
    sports: ['tennis', 'swimming'],
    totals: { kcal: 720, protein: 40, carbs: 95, fat: 12 },
    ingredients: [
      { foodId: 'california-rolls', name: 'California rolls', baseG: 280 },
      { foodId: 'rice-sushi',       name: 'Riz à sushi',      baseG: 80 },
      { foodId: 'tuna-raw',         name: 'Thon cru',         baseG: 100 },
      { foodId: 'soy-sauce',        name: 'Sauce soja',       baseG: 20 },
    ],
    recipe: {
      prepMinutes: 15,
      cookMinutes: 10,
      servings: 1,
      steps: [
        'Rince le riz à sushi 3 fois puis cuis-le selon les indications du paquet.',
        'Assaisonne le riz tiède avec vinaigre de riz, sucre, sel et étale-le pour le refroidir.',
        'Coupe le thon en cubes ou en fines tranches selon ta préférence.',
        'Pour les California rolls : pose une feuille de nori sur un tapis, étale du riz, retourne.',
        'Garnis de surimi, avocat, concombre, roule fermement à l\'aide du tapis.',
        'Tranche les rolls en 6-8 morceaux avec un couteau humide.',
        'Sers le tout avec sauce soja, wasabi et gingembre mariné.',
      ],
      tips: 'Si trop long à préparer, achète des rolls tout faits au food court.',
    },
    image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600&h=400&fit=crop',
  },
  {
    id: 'steak-plate',
    name: 'Steak, pommes de terre & légumes',
    type: 'lunch',
    objectives: ['high-protein', 'mass-gain'],
    sports: ['football', 'basketball'],
    totals: { kcal: 890, protein: 60, carbs: 62, fat: 32 },
    ingredients: [
      { foodId: 'beef-steak',    name: 'Steak (faux-filet)', baseG: 220 },
      { foodId: 'potatoes',      name: 'Pommes de terre',    baseG: 280 },
      { foodId: 'mixed-veggies', name: 'Légumes (haricots verts)', baseG: 150 },
      { foodId: 'butter',        name: 'Beurre',             baseG: 10 },
    ],
    recipe: {
      prepMinutes: 8,
      cookMinutes: 20,
      servings: 1,
      steps: [
        'Sors le steak du frigo 30 min avant pour qu\'il soit à température ambiante.',
        'Épluche et coupe les pommes de terre, cuis-les à l\'eau salée 15 min jusqu\'à tendreté.',
        'Vapeur ou cocotte minute pour les haricots verts (6 min).',
        'Assaisonne le steak généreusement sel et poivre sur les deux faces.',
        'Chauffe une poêle en fonte à feu vif avec un peu d\'huile.',
        'Saisis le steak 3 min par face pour une cuisson saignante, ajoute une noix de beurre à la fin.',
        'Laisse reposer le steak 5 min sous une feuille d\'alu, dresse avec pommes de terre et légumes.',
      ],
      tips: 'Le repos après cuisson est crucial pour un steak tendre et juteux.',
    },
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop',
  },
  {
    id: 'recovery-plate',
    name: 'Poulet, riz & légumes vapeur',
    type: 'lunch',
    objectives: ['recovery', 'post-training'],
    sports: ['soccer', 'basketball', 'tennis'],
    totals: { kcal: 760, protein: 48, carbs: 82, fat: 15 },
    ingredients: [
      { foodId: 'chicken-breast', name: 'Poulet',         baseG: 170 },
      { foodId: 'rice-white',     name: 'Riz cuit',       baseG: 240 },
      { foodId: 'mixed-veggies',  name: 'Légumes vapeur', baseG: 180 },
      { foodId: 'mixed-fruits',   name: 'Fruit',          baseG: 130 },
    ],
    recipe: {
      prepMinutes: 6,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Lance la cuisson du riz dans une casserole d\'eau salée.',
        'Coupe le poulet en escalopes, assaisonne avec sel, poivre, citron.',
        'Fais cuire le poulet à la poêle 4 min de chaque côté à feu moyen.',
        'Cuis les légumes à la vapeur 8 min pour préserver vitamines et minéraux.',
        'Dresse l\'assiette : riz, poulet tranché, légumes.',
        'Sers avec le fruit frais coupé en dessert pour la recharge en glucides simples.',
      ],
      tips: 'À consommer dans les 90 min après l\'entraînement pour maximiser la récup.',
    },
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
  },
  {
    id: 'campus-wrap',
    name: 'Wrap poulet César',
    type: 'lunch',
    objectives: ['maintenance', 'light'],
    sports: ['tennis', 'soccer'],
    totals: { kcal: 740, protein: 45, carbs: 68, fat: 25 },
    ingredients: [
      { foodId: 'chicken-caesar-wrap', name: 'Chicken Caesar wrap', baseG: 280 },
      { foodId: 'mixed-fruits',        name: 'Fruit',               baseG: 130 },
      { foodId: 'greek-yogurt',        name: 'Yaourt grec',         baseG: 150 },
    ],
    recipe: {
      prepMinutes: 10,
      cookMinutes: 8,
      servings: 1,
      steps: [
        'Coupe le blanc de poulet en lanières, assaisonne sel-poivre.',
        'Fais griller les lanières 4 min par face dans une poêle chaude.',
        'Lave et essore la salade romaine, taille en lanières.',
        'Mélange la salade avec sauce Caesar, parmesan râpé et croûtons.',
        'Réchauffe la tortilla 20 sec au micro-ondes pour la rendre souple.',
        'Garnis de salade Caesar et de poulet grillé, roule fermement.',
        'Coupe en deux en diagonale, sers avec fruit et yaourt grec.',
      ],
      tips: 'Parfait à emporter entre deux cours sur le campus.',
    },
    image: 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?w=600&h=400&fit=crop',
  },

  /* =========================================================
   * DÎNERS (15)
   * ========================================================= */
  {
    id: 'recovery-dinner',
    name: 'Poulet, riz basmati & légumes',
    type: 'dinner',
    objectives: ['recovery', 'post-training'],
    sports: ['soccer', 'basketball', 'tennis'],
    totals: { kcal: 760, protein: 52, carbs: 80, fat: 14 },
    ingredients: [
      { foodId: 'chicken-breast', name: 'Poulet',       baseG: 180 },
      { foodId: 'rice-basmati',   name: 'Riz basmati cuit', baseG: 250 },
      { foodId: 'mixed-veggies',  name: 'Légumes vapeur',baseG: 180 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 18,
      servings: 1,
      steps: [
        'Lance le riz basmati (15 min dans 1,5 fois son volume d\'eau salée).',
        'Coupe le poulet en escalopes, assaisonne sel, poivre, curcuma.',
        'Fais cuire le poulet à la poêle 4-5 min de chaque côté à feu moyen.',
        'Cuis les légumes à la vapeur 8-10 min selon leur taille.',
        'Égrène le riz à la fourchette, dresse au centre de l\'assiette.',
        'Tranche le poulet, dispose avec les légumes autour.',
        'Termine par un filet d\'huile d\'olive et un trait de citron.',
      ],
      tips: 'Idéal le soir après une grosse séance pour reconstituer les réserves.',
    },
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
  },
  {
    id: 'mass-plate',
    name: 'Steak, pâtes & avocat',
    type: 'dinner',
    objectives: ['mass-gain'],
    sports: ['football', 'basketball'],
    totals: { kcal: 980, protein: 58, carbs: 92, fat: 35 },
    ingredients: [
      { foodId: 'beef-steak', name: 'Steak',     baseG: 200 },
      { foodId: 'pasta',      name: 'Pâtes',     baseG: 220 },
      { foodId: 'avocado',    name: 'Avocat',    baseG: 100 },
      { foodId: 'olive-oil',  name: 'Huile d\'olive', baseG: 10 },
    ],
    recipe: {
      prepMinutes: 7,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Porte une grande casserole d\'eau salée à ébullition et cuis les pâtes al dente.',
        'Sors le steak du frigo, assaisonne sel, poivre, ail en poudre.',
        'Chauffe une poêle bien fort, saisis le steak 3 min par face.',
        'Réserve le steak sous papier alu pour le repos (5 min).',
        'Égoutte les pâtes en gardant un peu d\'eau de cuisson, mélange avec huile d\'olive et avocat écrasé.',
        'Tranche le steak en lamelles épaisses.',
        'Dresse les pâtes au centre, dépose le steak tranché et quelques cubes d\'avocat dessus.',
      ],
      tips: 'L\'avocat apporte des bonnes graisses qui boostent le total calorique sans alourdir.',
    },
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop',
  },
  {
    id: 'lean-night',
    name: 'Saumon & patate douce',
    type: 'dinner',
    objectives: ['cutting'],
    sports: ['tennis', 'soccer', 'swimming'],
    totals: { kcal: 690, protein: 45, carbs: 42, fat: 30 },
    ingredients: [
      { foodId: 'salmon',        name: 'Saumon',         baseG: 180 },
      { foodId: 'mixed-veggies', name: 'Légumes (brocoli, asperges)', baseG: 200 },
      { foodId: 'sweet-potato',  name: 'Patate douce',   baseG: 180 },
      { foodId: 'olive-oil',     name: 'Huile d\'olive', baseG: 8 },
    ],
    recipe: {
      prepMinutes: 8,
      cookMinutes: 22,
      servings: 1,
      steps: [
        'Préchauffe le four à 200 °C.',
        'Coupe la patate douce en cubes, mélange avec huile, paprika, sel.',
        'Enfourne 20 min en remuant à mi-cuisson.',
        'Assaisonne le saumon avec sel, poivre, aneth et un trait de citron.',
        'Pose-le sur une feuille de papier sulfurisé au four pour les 10 dernières minutes.',
        'Pendant ce temps, fais sauter les légumes à la poêle avec un peu d\'ail 6 min.',
        'Dresse l\'assiette : saumon, légumes verts, patate douce, filet d\'huile d\'olive.',
      ],
      tips: 'Combo riche en oméga-3 et fibres pour rester rassasié sans excès calorique.',
    },
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
  },
  {
    id: 'athlete-rice',
    name: 'Dinde sautée, riz & légumes',
    type: 'dinner',
    objectives: ['maintenance'],
    sports: ['soccer', 'basketball', 'tennis'],
    totals: { kcal: 740, protein: 50, carbs: 76, fat: 16 },
    ingredients: [
      { foodId: 'turkey-breast', name: 'Dinde',         baseG: 170 },
      { foodId: 'rice-white',    name: 'Riz cuit',      baseG: 240 },
      { foodId: 'mixed-veggies', name: 'Légumes sautés',baseG: 180 },
    ],
    recipe: {
      prepMinutes: 6,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Lance la cuisson du riz dans une casserole d\'eau salée (12 min).',
        'Coupe la dinde en lanières, assaisonne sel, poivre, thym.',
        'Fais sauter la dinde 6 min dans une poêle huilée à feu vif.',
        'Ajoute les légumes coupés et un peu d\'ail, sauté encore 5 min.',
        'Verse un trait de sauce soja en fin de cuisson.',
        'Dresse le riz dans un bol, ajoute le mélange dinde-légumes par-dessus.',
      ],
      tips: 'Plat simple et équilibré, parfait en routine de semaine.',
    },
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop',
  },
  {
    id: 'pasta-night',
    name: 'Pâtes au poulet, sauce tomate',
    type: 'dinner',
    objectives: ['endurance', 'pre-match'],
    sports: ['soccer', 'track', 'tennis'],
    totals: { kcal: 860, protein: 54, carbs: 102, fat: 18 },
    ingredients: [
      { foodId: 'pasta',          name: 'Pâtes',        baseG: 260 },
      { foodId: 'chicken-breast', name: 'Poulet',       baseG: 170 },
      { foodId: 'tomato-sauce',   name: 'Sauce tomate', baseG: 150 },
      { foodId: 'parmesan',       name: 'Parmesan',     baseG: 20 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Mets une grande casserole d\'eau salée à bouillir.',
        'Coupe le poulet en cubes, assaisonne sel, poivre, origan.',
        'Fais cuire le poulet à la poêle 6 min à feu moyen-vif jusqu\'à coloration.',
        'Ajoute la sauce tomate sur le poulet, laisse mijoter 5 min à feu doux.',
        'Plonge les pâtes dans l\'eau bouillante et cuis al dente.',
        'Égoutte les pâtes, mélange-les avec la sauce poulet-tomate.',
        'Sers généreusement parsemé de parmesan râpé et de basilic frais.',
      ],
      tips: 'Repas idéal la veille d\'un match pour charger les réserves de glycogène.',
    },
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&h=400&fit=crop',
  },
  {
    id: 'protein-bowl',
    name: 'Bowl steak, riz & haricots',
    type: 'dinner',
    objectives: ['high-protein', 'mass-gain'],
    sports: ['football', 'basketball'],
    totals: { kcal: 920, protein: 60, carbs: 78, fat: 28 },
    ingredients: [
      { foodId: 'rice-white',  name: 'Riz cuit',       baseG: 220 },
      { foodId: 'beef-steak',  name: 'Steak',          baseG: 200 },
      { foodId: 'black-beans', name: 'Haricots noirs', baseG: 150 },
      { foodId: 'avocado',     name: 'Avocat',         baseG: 60 },
    ],
    recipe: {
      prepMinutes: 6,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Lance la cuisson du riz dans une casserole d\'eau salée.',
        'Assaisonne le steak sel, poivre, paprika fumé.',
        'Fais saisir le steak 3 min par face dans une poêle bien chaude.',
        'Laisse reposer le steak 4 min sous papier alu.',
        'Réchauffe les haricots noirs avec une pincée de cumin et un peu d\'ail.',
        'Tranche le steak en lamelles.',
        'Dresse le riz dans un grand bol, ajoute steak, haricots, lamelles d\'avocat.',
      ],
      tips: 'Combo 60 g de protéines : top pour la croissance musculaire en récupération.',
    },
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&h=400&fit=crop',
  },
  {
    id: 'salmon-recovery',
    name: 'Saumon, quinoa & légumes rôtis',
    type: 'dinner',
    objectives: ['recovery'],
    sports: ['swimming', 'soccer', 'track'],
    totals: { kcal: 810, protein: 48, carbs: 58, fat: 32 },
    ingredients: [
      { foodId: 'salmon',        name: 'Saumon',       baseG: 200 },
      { foodId: 'quinoa',        name: 'Quinoa cuit',  baseG: 200 },
      { foodId: 'mixed-veggies', name: 'Légumes rôtis',baseG: 180 },
      { foodId: 'olive-oil',     name: 'Huile d\'olive', baseG: 10 },
    ],
    recipe: {
      prepMinutes: 8,
      cookMinutes: 20,
      servings: 1,
      steps: [
        'Préchauffe le four à 200 °C.',
        'Rince le quinoa et cuis-le 12 min dans 2 fois son volume d\'eau salée.',
        'Coupe les légumes en morceaux, enrobe d\'huile, herbes de Provence, sel.',
        'Enfourne les légumes 18 min en remuant à mi-cuisson.',
        'Assaisonne le saumon, pose-le sur les légumes pour les 8 dernières minutes au four.',
        'Égrène le quinoa à la fourchette dans une assiette creuse.',
        'Dresse saumon et légumes rôtis sur le quinoa, filet d\'huile d\'olive citronnée.',
      ],
      tips: 'Quinoa = protéines complètes végétales : parfait avec le saumon.',
    },
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
  },
  {
    id: 'chicken-power',
    name: 'Poulet, pommes de terre & légumes',
    type: 'dinner',
    objectives: ['performance'],
    sports: ['soccer'],
    totals: { kcal: 780, protein: 58, carbs: 65, fat: 18 },
    ingredients: [
      { foodId: 'chicken-breast', name: 'Poulet',         baseG: 220 },
      { foodId: 'potatoes',       name: 'Pommes de terre',baseG: 280 },
      { foodId: 'mixed-veggies',  name: 'Légumes verts',  baseG: 180 },
    ],
    recipe: {
      prepMinutes: 8,
      cookMinutes: 25,
      servings: 1,
      steps: [
        'Préchauffe le four à 210 °C.',
        'Coupe les pommes de terre en quartiers, enrobe d\'huile, romarin, sel.',
        'Enfourne 25 min en retournant à mi-cuisson.',
        'Assaisonne le poulet généreusement avec sel, poivre, ail, thym.',
        'Fais griller le poulet 5 min par face dans une poêle à feu moyen-vif.',
        'Cuis les légumes à la vapeur ou à la poêle 6 min.',
        'Dresse l\'assiette : poulet tranché, pommes de terre rôties, légumes.',
      ],
      tips: 'Plat dense en protéines pour soutenir la performance répétée du foot.',
    },
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
  },
  {
    id: 'basketball-fuel',
    name: 'Bowl viande hachée, riz & avocat',
    type: 'dinner',
    objectives: ['performance', 'mass-gain'],
    sports: ['basketball'],
    totals: { kcal: 950, protein: 54, carbs: 98, fat: 30 },
    ingredients: [
      { foodId: 'rice-white', name: 'Riz cuit',  baseG: 250 },
      { foodId: 'beef-lean',  name: 'Viande hachée maigre', baseG: 180 },
      { foodId: 'avocado',    name: 'Avocat',    baseG: 100 },
      { foodId: 'mixed-veggies', name: 'Légumes', baseG: 130 },
    ],
    recipe: {
      prepMinutes: 6,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Lance la cuisson du riz.',
        'Fais revenir la viande hachée à feu vif, émiette à la spatule.',
        'Assaisonne avec sel, poivre, paprika fumé et un peu d\'ail.',
        'Quand la viande est dorée (6 min), ajoute les légumes coupés et sauté 4 min.',
        'Tranche l\'avocat en lamelles fines.',
        'Dresse le riz dans un grand bol, ajoute la viande-légumes.',
        'Couronne de lamelles d\'avocat et de coriandre fraîche.',
      ],
      tips: 'Riche en glucides complexes pour tenir les 4 quart-temps.',
    },
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=crop',
  },
  {
    id: 'tennis-recovery',
    name: 'Pâtes au poulet & légumes',
    type: 'dinner',
    objectives: ['recovery'],
    sports: ['tennis'],
    totals: { kcal: 840, protein: 52, carbs: 88, fat: 18 },
    ingredients: [
      { foodId: 'chicken-breast', name: 'Poulet',  baseG: 180 },
      { foodId: 'pasta',          name: 'Pâtes',   baseG: 230 },
      { foodId: 'mixed-veggies',  name: 'Légumes (courgette, tomate cerise)', baseG: 180 },
      { foodId: 'olive-oil',      name: 'Huile d\'olive', baseG: 10 },
    ],
    recipe: {
      prepMinutes: 6,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Mets l\'eau des pâtes à bouillir avec une bonne pincée de sel.',
        'Coupe le poulet en lanières, assaisonne sel, poivre, herbes italiennes.',
        'Fais sauter le poulet 5 min dans une poêle huilée jusqu\'à coloration dorée.',
        'Ajoute les légumes coupés (courgette en rondelles, tomates cerises coupées en 2).',
        'Laisse sauter 5 min en remuant régulièrement.',
        'Cuis les pâtes al dente, égoutte en gardant un peu d\'eau de cuisson.',
        'Mélange pâtes, poulet et légumes dans la poêle, ajuste avec l\'eau, parsème de parmesan.',
      ],
      tips: 'Idéal après un long match en 3 sets pour reconstituer le glycogène.',
    },
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&h=400&fit=crop',
  },
  {
    id: 'track-dinner',
    name: 'Saumon, riz & fruits',
    type: 'dinner',
    objectives: ['endurance', 'recovery'],
    sports: ['track'],
    totals: { kcal: 890, protein: 50, carbs: 100, fat: 24 },
    ingredients: [
      { foodId: 'rice-white',   name: 'Riz cuit',   baseG: 260 },
      { foodId: 'salmon',       name: 'Saumon',     baseG: 180 },
      { foodId: 'mixed-fruits', name: 'Fruits frais',baseG: 200 },
      { foodId: 'olive-oil',    name: 'Huile d\'olive', baseG: 8 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Lance la cuisson du riz dans une casserole d\'eau salée (12 min).',
        'Assaisonne le saumon sel, poivre, citron, aneth.',
        'Chauffe une poêle à feu moyen avec un filet d\'huile.',
        'Pose le saumon côté peau, cuis 4 min sans toucher, puis retourne et cuis 3 min.',
        'Égrène le riz à la fourchette dans un grand bol.',
        'Dépose le saumon sur le riz, défais-le en gros morceaux.',
        'Sers avec les fruits frais coupés en dessert pour la recharge glucidique.',
      ],
      tips: 'Les sprinters et coureurs ont besoin de glucides en abondance.',
    },
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&h=400&fit=crop',
  },
  {
    id: 'light-dinner',
    name: 'Omelette, salade & pain complet',
    type: 'dinner',
    objectives: ['light', 'cutting'],
    sports: ['tennis', 'swimming'],
    totals: { kcal: 620, protein: 40, carbs: 42, fat: 22 },
    ingredients: [
      { foodId: 'eggs-whole',    name: 'Œufs',         baseG: 180 },
      { foodId: 'salad-greens',  name: 'Salade verte', baseG: 150 },
      { foodId: 'bread-whole',   name: 'Pain complet', baseG: 80 },
      { foodId: 'olive-oil',     name: 'Huile d\'olive', baseG: 10 },
      { foodId: 'cheese-shred',  name: 'Fromage râpé', baseG: 20 },
    ],
    recipe: {
      prepMinutes: 5,
      cookMinutes: 6,
      servings: 1,
      steps: [
        'Bats les œufs avec sel, poivre et le fromage râpé.',
        'Chauffe une poêle anti-adhésive à feu moyen avec un peu d\'huile.',
        'Verse les œufs, laisse prendre 2 min puis replie en omelette baveuse.',
        'Lave la salade, mélange avec une vinaigrette huile d\'olive, vinaigre, moutarde.',
        'Toaste les tranches de pain complet.',
        'Dresse l\'assiette : omelette pliée, salade verte à côté, pain complet en accompagnement.',
      ],
      tips: 'Idéal en fin de journée si tu as déjà bien mangé au déjeuner.',
    },
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop',
  },
  {
    id: 'campus-comfort',
    name: 'Boulettes, pâtes & sauce tomate',
    type: 'dinner',
    objectives: ['mass-gain', 'maintenance'],
    sports: ['football', 'baseball'],
    totals: { kcal: 940, protein: 48, carbs: 98, fat: 32 },
    ingredients: [
      { foodId: 'meatballs',     name: 'Boulettes de viande', baseG: 200 },
      { foodId: 'pasta',         name: 'Pâtes',               baseG: 240 },
      { foodId: 'tomato-sauce',  name: 'Sauce tomate',        baseG: 150 },
      { foodId: 'mixed-veggies', name: 'Légumes',             baseG: 120 },
      { foodId: 'parmesan',      name: 'Parmesan',            baseG: 20 },
    ],
    recipe: {
      prepMinutes: 10,
      cookMinutes: 20,
      servings: 1,
      steps: [
        'Forme les boulettes avec viande hachée, chapelure, œuf, ail, sel, poivre.',
        'Roule-les en boules régulières et fais-les dorer 8 min dans une poêle huilée.',
        'Verse la sauce tomate sur les boulettes, ajoute basilic et laisse mijoter 10 min.',
        'Cuis les pâtes al dente dans une grande casserole d\'eau salée.',
        'Cuis les légumes à la vapeur ou à la poêle en accompagnement.',
        'Égoutte les pâtes, mélange-les rapidement avec un peu de sauce tomate.',
        'Dresse les pâtes, dépose les boulettes nappées de sauce, parsème de parmesan, légumes à côté.',
      ],
      tips: 'Cuisine le double pour avoir des restes pour le lendemain midi.',
    },
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600&h=400&fit=crop',
  },
  {
    id: 'evening-bowl',
    name: 'Bowl tofu, riz & avocat',
    type: 'dinner',
    objectives: ['vegan'],
    sports: ['soccer', 'tennis', 'track'],
    totals: { kcal: 710, protein: 35, carbs: 76, fat: 24 },
    ingredients: [
      { foodId: 'rice-white',    name: 'Riz cuit', baseG: 230 },
      { foodId: 'tofu',          name: 'Tofu',     baseG: 200 },
      { foodId: 'mixed-veggies', name: 'Légumes (brocoli, carotte)', baseG: 150 },
      { foodId: 'avocado',       name: 'Avocat',   baseG: 80 },
      { foodId: 'soy-sauce',     name: 'Sauce soja', baseG: 15 },
    ],
    recipe: {
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      steps: [
        'Égoutte le tofu, presse-le dans un torchon 10 min pour retirer l\'eau.',
        'Coupe le tofu en cubes, mélange avec sauce soja, ail, gingembre.',
        'Fais sauter le tofu dans une poêle bien chaude 6-8 min jusqu\'à coloration dorée.',
        'Lance la cuisson du riz en parallèle.',
        'Fais sauter les légumes 5 min avec un peu d\'huile de sésame.',
        'Tranche l\'avocat en lamelles.',
        'Dresse le riz, ajoute tofu doré, légumes sautés, avocat et un trait de sauce soja.',
      ],
      tips: 'Le tofu mariné absorbe mieux les saveurs : prépare-le 30 min à l\'avance si possible.',
    },
    image: 'https://images.unsplash.com/photo-1583224994076-ae3a3aa3a4e4?w=600&h=400&fit=crop',
  },
  {
    id: 'night-recovery',
    name: 'Yaourt, porridge & beurre cacahuète',
    type: 'dinner',
    objectives: ['recovery', 'light'],
    sports: ['soccer', 'basketball', 'tennis'],
    totals: { kcal: 650, protein: 38, carbs: 62, fat: 20 },
    ingredients: [
      { foodId: 'greek-yogurt',  name: 'Yaourt grec',     baseG: 250 },
      { foodId: 'mixed-fruits',  name: 'Fruits frais',    baseG: 150 },
      { foodId: 'oatmeal',       name: 'Oatmeal cuit',    baseG: 180 },
      { foodId: 'peanut-butter', name: 'Beurre de cacahuète', baseG: 25 },
      { foodId: 'honey',         name: 'Miel',            baseG: 10 },
    ],
    recipe: {
      prepMinutes: 4,
      cookMinutes: 5,
      servings: 1,
      steps: [
        'Cuis les flocons d\'avoine dans 1,5 fois leur volume de lait à feu doux 4 min.',
        'Transvase l\'oatmeal dans un grand bol et laisse tiédir.',
        'Ajoute le yaourt grec par-dessus en couche généreuse.',
        'Délaye le beurre de cacahuète avec une cuillère de lait chaud pour le rendre coulant.',
        'Verse le beurre de cacahuète sur le yaourt.',
        'Dépose les fruits frais coupés et arrose d\'un trait de miel.',
      ],
      tips: 'Le tryptophane du lait + caséine du yaourt = sommeil et récup nocturne optimaux.',
    },
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop',
  },

  /* =========================================================
   * SNACKS (15)
   * ========================================================= */
  {
    id: 'quick-protein',
    name: 'Yaourt grec & banane',
    type: 'snack',
    objectives: ['high-protein', 'light'],
    sports: ['soccer', 'tennis', 'basketball'],
    totals: { kcal: 260, protein: 22, carbs: 32, fat: 2 },
    ingredients: [
      { foodId: 'greek-yogurt', name: 'Yaourt grec', baseG: 200 },
      { foodId: 'banana',       name: 'Banane',      baseG: 120 },
    ],
    recipe: {
      prepMinutes: 2,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Verse le yaourt grec dans un bol.',
        'Épluche et tranche la banane en rondelles.',
        'Dépose les rondelles de banane sur le yaourt.',
        'Optionnel : ajoute une pointe de cannelle ou un trait de miel.',
      ],
      tips: 'Choisis un yaourt grec 0 % ou 2 % pour minimiser les calories.',
    },
    image: 'https://images.unsplash.com/photo-1622003275667-9d76aaeaa9c4?w=600&h=400&fit=crop',
  },
  {
    id: 'match-snack',
    name: 'Bagel au beurre de cacahuète',
    type: 'snack',
    objectives: ['pre-match', 'endurance'],
    sports: ['soccer', 'basketball', 'tennis'],
    totals: { kcal: 420, protein: 14, carbs: 48, fat: 18 },
    ingredients: [
      { foodId: 'bagel-plain',   name: 'Bagel',              baseG: 100 },
      { foodId: 'peanut-butter', name: 'Beurre de cacahuète',baseG: 30 },
    ],
    recipe: {
      prepMinutes: 3,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Coupe le bagel en deux à l\'horizontale.',
        'Toaste les deux moitiés au grille-pain ou à la poêle sèche 2 min.',
        'Tartine généreusement chaque moitié de beurre de cacahuète.',
        'Referme le bagel et coupe en deux pour faciliter le transport.',
      ],
      tips: 'À manger 60-90 min avant le match pour avoir l\'énergie sans alourdir.',
    },
    image: 'https://www.themealdb.com/images/ingredients/Banana.png',
  },
  {
    id: 'recovery-snack',
    name: 'Lait chocolaté & barre protéinée',
    type: 'snack',
    objectives: ['post-training', 'recovery'],
    sports: ['soccer', 'basketball', 'football'],
    totals: { kcal: 380, protein: 28, carbs: 42, fat: 10 },
    ingredients: [
      { foodId: 'chocolate-milk', name: 'Lait chocolaté',  baseG: 300 },
      { foodId: 'protein-bar',    name: 'Barre protéinée', baseG: 60 },
    ],
    recipe: {
      prepMinutes: 1,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Sers le lait chocolaté frais dans un grand verre.',
        'Déballe la barre protéinée.',
        'Consomme les deux dans les 30 min suivant l\'effort.',
      ],
      tips: 'Ratio glucides/protéines parfait pour la fenêtre anabolique post-training.',
    },
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=600&h=400&fit=crop',
  },
  {
    id: 'energy-mix',
    name: 'Granola, fruits & amandes',
    type: 'snack',
    objectives: ['endurance'],
    sports: ['track', 'soccer', 'tennis'],
    totals: { kcal: 450, protein: 12, carbs: 52, fat: 20 },
    ingredients: [
      { foodId: 'granola',      name: 'Granola',     baseG: 60 },
      { foodId: 'mixed-fruits', name: 'Fruits frais',baseG: 130 },
      { foodId: 'almonds',      name: 'Amandes',     baseG: 30 },
    ],
    recipe: {
      prepMinutes: 3,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Verse le granola dans un bol ou un Tupperware nomade.',
        'Coupe les fruits frais en petits morceaux et ajoute-les au granola.',
        'Termine avec une poignée d\'amandes entières ou effilées.',
        'Mélange et consomme directement ou emporte pour plus tard.',
      ],
      tips: 'Format parfait à glisser dans le sac avant un long entraînement.',
    },
    image: 'https://images.unsplash.com/photo-1604908554027-9e8b2c8b6e6d?w=600&h=400&fit=crop',
  },
  {
    id: 'protein-shake',
    name: 'Shake whey, lait & banane',
    type: 'snack',
    objectives: ['high-protein', 'post-training'],
    sports: ['football', 'basketball', 'soccer'],
    totals: { kcal: 340, protein: 35, carbs: 30, fat: 8 },
    ingredients: [
      { foodId: 'whey-protein', name: 'Whey protéine', baseG: 35 },
      { foodId: 'milk',         name: 'Lait',          baseG: 300 },
      { foodId: 'banana',       name: 'Banane',        baseG: 120 },
    ],
    recipe: {
      prepMinutes: 3,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Verse le lait dans un blender.',
        'Ajoute la mesure de whey et la banane coupée en rondelles.',
        'Mixe 30 sec jusqu\'à obtenir une texture lisse et mousseuse.',
        'Sers immédiatement dans un grand verre ou un shaker.',
      ],
      tips: 'Ajoute 5 glaçons pour une texture plus fraîche et épaisse.',
    },
    image: 'https://images.unsplash.com/photo-1622003275667-9d76aaeaa9c4?w=600&h=400&fit=crop',
  },
  {
    id: 'lean-snack',
    name: 'Yaourt grec & fraises',
    type: 'snack',
    objectives: ['cutting', 'light'],
    sports: ['tennis', 'soccer', 'track'],
    totals: { kcal: 180, protein: 20, carbs: 18, fat: 1 },
    ingredients: [
      { foodId: 'greek-yogurt-0', name: 'Yaourt grec 0%', baseG: 200 },
      { foodId: 'strawberries',   name: 'Fraises',        baseG: 150 },
    ],
    recipe: {
      prepMinutes: 3,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Lave et équeute les fraises, coupe-les en quartiers.',
        'Verse le yaourt grec 0 % dans un bol.',
        'Dépose les fraises sur le yaourt.',
        'Optionnel : ajoute quelques feuilles de menthe pour le parfum.',
      ],
      tips: 'Snack ultra léger : 180 kcal pour 20 g de protéines.',
    },
    image: 'https://www.themealdb.com/images/ingredients/Apple.png',
  },
  {
    id: 'mass-snack',
    name: 'Bagel, beurre cacahuète & banane',
    type: 'snack',
    objectives: ['mass-gain'],
    sports: ['football', 'basketball'],
    totals: { kcal: 620, protein: 18, carbs: 72, fat: 28 },
    ingredients: [
      { foodId: 'bagel-plain',   name: 'Bagel',               baseG: 110 },
      { foodId: 'peanut-butter', name: 'Beurre de cacahuète', baseG: 40 },
      { foodId: 'banana',        name: 'Banane',              baseG: 120 },
    ],
    recipe: {
      prepMinutes: 3,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Coupe le bagel en deux et toaste les deux moitiés.',
        'Tartine généreusement chaque moitié de beurre de cacahuète.',
        'Tranche la banane en rondelles.',
        'Dispose les rondelles sur l\'une des moitiés, referme le bagel pour un mini-sandwich.',
      ],
      tips: 'Combo dense en calories pour les athlètes qui veulent prendre du poids.',
    },
    image: 'https://www.themealdb.com/images/ingredients/Peanut-Butter.png',
  },
  {
    id: 'campus-fuel',
    name: 'Trail mix & pomme',
    type: 'snack',
    objectives: ['endurance'],
    sports: ['soccer', 'tennis', 'track'],
    totals: { kcal: 390, protein: 10, carbs: 42, fat: 20 },
    ingredients: [
      { foodId: 'trail-mix', name: 'Trail mix', baseG: 60 },
      { foodId: 'apple',     name: 'Pomme',     baseG: 180 },
    ],
    recipe: {
      prepMinutes: 1,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Verse le trail mix dans un petit Tupperware ou un sac réutilisable.',
        'Lave la pomme et croque dedans entière, ou tranche-la en quartiers.',
        'Consomme alternativement entre deux cours pour tenir l\'après-midi.',
      ],
      tips: 'Garde toujours une portion de trail mix dans ton sac à dos.',
    },
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&h=400&fit=crop',
  },
  {
    id: 'sweet-recovery',
    name: 'Rice Krispie & lait',
    type: 'snack',
    objectives: ['post-training', 'recovery'],
    sports: ['soccer', 'basketball'],
    totals: { kcal: 310, protein: 12, carbs: 44, fat: 9 },
    ingredients: [
      { foodId: 'rice-krispie', name: 'Rice Krispie treat', baseG: 60 },
      { foodId: 'milk',         name: 'Lait',               baseG: 300 },
    ],
    recipe: {
      prepMinutes: 1,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Sers le lait bien frais dans un grand verre.',
        'Déballe le Rice Krispie treat.',
        'Mange-le en alternant avec des gorgées de lait pour la recharge glucidique.',
      ],
      tips: 'Sucres rapides + protéines du lait : recharge glycogène express.',
    },
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&h=400&fit=crop',
  },
  {
    id: 'athlete-bowl',
    name: 'Bowl yaourt, granola & myrtilles',
    type: 'snack',
    objectives: ['maintenance', 'high-protein'],
    sports: ['soccer', 'basketball', 'tennis'],
    totals: { kcal: 430, protein: 28, carbs: 48, fat: 12 },
    ingredients: [
      { foodId: 'greek-yogurt', name: 'Yaourt grec', baseG: 250 },
      { foodId: 'granola',      name: 'Granola',     baseG: 40 },
      { foodId: 'blueberries',  name: 'Myrtilles',   baseG: 100 },
    ],
    recipe: {
      prepMinutes: 3,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Verse le yaourt grec dans un bol.',
        'Parsème généreusement de granola par-dessus.',
        'Lave les myrtilles et dépose-les sur le granola.',
        'Optionnel : un trait de miel pour adoucir.',
      ],
      tips: 'Antioxydants des myrtilles + protéines : combo récup et anti-inflammatoire.',
    },
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&h=400&fit=crop',
  },
  {
    id: 'fast-energy',
    name: 'Bretzels, jus & fruits',
    type: 'snack',
    objectives: ['pre-match', 'endurance'],
    sports: ['soccer', 'track', 'tennis'],
    totals: { kcal: 320, protein: 6, carbs: 68, fat: 2 },
    ingredients: [
      { foodId: 'pretzels',     name: 'Pretzels',     baseG: 50 },
      { foodId: 'orange-juice', name: 'Jus de fruits',baseG: 250 },
      { foodId: 'mixed-fruits', name: 'Fruits frais', baseG: 150 },
    ],
    recipe: {
      prepMinutes: 2,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Verse les pretzels dans un petit bol.',
        'Lave et coupe les fruits frais en morceaux (raisin, banane, pomme).',
        'Sers le jus dans un grand verre.',
        'Alterne entre pretzels, fruits et jus pour bien t\'hydrater.',
      ],
      tips: 'Pretzels = sel + glucides rapides : top juste avant un effort intense.',
    },
    image: 'https://images.unsplash.com/photo-1592151450334-c64aeac0b80a?w=600&h=400&fit=crop',
  },
  {
    id: 'night-protein',
    name: 'Yaourt & beurre de cacahuète',
    type: 'snack',
    objectives: ['high-protein', 'recovery'],
    sports: ['football', 'basketball', 'soccer'],
    totals: { kcal: 340, protein: 30, carbs: 12, fat: 18 },
    ingredients: [
      { foodId: 'greek-yogurt',  name: 'Yaourt grec',         baseG: 250 },
      { foodId: 'peanut-butter', name: 'Beurre de cacahuète', baseG: 25 },
    ],
    recipe: {
      prepMinutes: 2,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Verse le yaourt grec dans un bol.',
        'Délaye légèrement le beurre de cacahuète avec une cuillère pour le rendre plus souple.',
        'Dépose le beurre de cacahuète sur le yaourt en swirl.',
        'Optionnel : saupoudre de cannelle ou ajoute quelques copeaux de chocolat noir.',
      ],
      tips: 'Caséine du yaourt = libération lente des protéines pendant le sommeil.',
    },
    image: 'https://images.unsplash.com/photo-1622003275667-9d76aaeaa9c4?w=600&h=400&fit=crop',
  },
  {
    id: 'power-fruit',
    name: 'Shake banane, whey & amandes',
    type: 'snack',
    objectives: ['performance', 'high-protein'],
    sports: ['soccer', 'basketball', 'tennis'],
    totals: { kcal: 410, protein: 30, carbs: 34, fat: 16 },
    ingredients: [
      { foodId: 'banana',       name: 'Banane',        baseG: 120 },
      { foodId: 'almonds',      name: 'Amandes',       baseG: 25 },
      { foodId: 'whey-protein', name: 'Whey protéine', baseG: 30 },
      { foodId: 'milk',         name: 'Lait',          baseG: 200 },
    ],
    recipe: {
      prepMinutes: 3,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Verse le lait dans le blender, ajoute la whey et la banane coupée.',
        'Mixe 30 sec jusqu\'à une texture lisse.',
        'Sers le shake dans un grand verre.',
        'Mange les amandes à côté pour le croquant et les bonnes graisses.',
      ],
      tips: 'Snack idéal 30 min avant un entraînement technique.',
    },
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=600&h=400&fit=crop',
  },
  {
    id: 'soccer-boost',
    name: 'Bagel à la confiture & fruits',
    type: 'snack',
    objectives: ['endurance', 'pre-match'],
    sports: ['soccer'],
    totals: { kcal: 430, protein: 11, carbs: 82, fat: 4 },
    ingredients: [
      { foodId: 'bagel-plain',  name: 'Bagel',         baseG: 110 },
      { foodId: 'jam',          name: 'Confiture',     baseG: 30 },
      { foodId: 'mixed-fruits', name: 'Fruits frais',  baseG: 180 },
    ],
    recipe: {
      prepMinutes: 3,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Coupe le bagel en deux et toaste-le.',
        'Tartine chaque moitié d\'une bonne couche de confiture.',
        'Lave et coupe les fruits frais en morceaux.',
        'Dispose le bagel et les fruits dans une assiette, mange à 90 min du match.',
      ],
      tips: 'Combo très riche en glucides simples : énergie immédiate pour 90 min de jeu.',
    },
    image: 'https://images.unsplash.com/photo-1592151450334-c64aeac0b80a?w=600&h=400&fit=crop',
  },
  {
    id: 'campus-crunch',
    name: 'Popcorn, beef jerky & pomme',
    type: 'snack',
    objectives: ['high-protein', 'light'],
    sports: ['tennis', 'baseball', 'soccer'],
    totals: { kcal: 350, protein: 24, carbs: 28, fat: 10 },
    ingredients: [
      { foodId: 'popcorn',    name: 'Popcorn nature', baseG: 30 },
      { foodId: 'beef-jerky', name: 'Beef jerky',     baseG: 50 },
      { foodId: 'apple',      name: 'Pomme',          baseG: 180 },
    ],
    recipe: {
      prepMinutes: 2,
      cookMinutes: 0,
      servings: 1,
      steps: [
        'Verse le popcorn dans un grand bol.',
        'Ajoute les morceaux de beef jerky à côté.',
        'Lave et tranche la pomme en quartiers.',
        'Consomme en alternant les textures pour une vraie pause coupe-faim.',
      ],
      tips: 'Choisis du popcorn nature sans beurre pour limiter les lipides.',
    },
    image: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=600&h=400&fit=crop',
  },
];

Object.freeze(window.MEALS_DB);
Object.freeze(window.MEAL_OBJECTIVES);
